Added location changes.

diff --git a/core/source/bootstrap b/core/source/bootstrap
--- a/core/source/bootstrap
+++ b/core/source/bootstrap
@@ -18,18 +18,32 @@ for program in automake aclocal autoconf autoheader
     }
 done
 
-# checking for the GLOBUS_INSTALL_PATH
+# checking for the GLOBUS_LOCATION
 
-if test "x$GLOBUS_INSTALL_PATH" = "x"; then
-    echo "ERROR Please specify GLOBUS_INSTALL_PATH" >&2
+if test "x$GLOBUS_LOCATION" = "x"; then
+    echo "ERROR Please specify GLOBUS_LOCATION" >&2
     exit 1
+fi
+
+config="-I ./config"
+
+if test ! -f "$GLOBUS_LOCATION/share/globus_aclocal/gpt_autoconf_macros.m4"; then
+    if test "x$GPT_LOCATION" = "x"; then
+        echo "ERROR Globus Packaging Tools not found" >&2
+        echo "ERROR either set GPT_LOCATION or install them in $GLOBUS_LOCATION" >&2
+        exit 1
+    else
+        config="$config -I $GPT_LOCATION/share/globus_aclocal"
+    fi
+else
+    config="$config -I $GLOBUS_LOCATION/share/globus_aclocal"
 fi
 
  echo "running libtoolize --automake --copy --force"
 libtoolize --automake --copy --force || error
 
-echo "running aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal  -I ./config"
-aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal -I ./config || error
+echo "running aclocal $config"
+aclocal $config || error
 
 if test -f acconfig.h ; then
  echo "running autoheader"
diff --git a/core/source/configure.in b/core/source/configure.in
--- a/core/source/configure.in
+++ b/core/source/configure.in
@@ -62,15 +62,19 @@ if test "$GLOBUS_THREADS" = "no" ; then
 fi
 AC_SUBST(GLOBUS_THREADS)
 
-# checking for the GLOBUS_INSTALL_PATH
+# checking for the GLOBUS_LOCATION
 
-if test "x$GLOBUS_INSTALL_PATH" = "x"; then
-    echo "ERROR Please specify GLOBUS_INSTALL_PATH" >&2
+if test "x$GLOBUS_LOCATION" = "x"; then
+    echo "ERROR Please specify GLOBUS_LOCATION" >&2
     exit 1
 fi
 
-prefix='$(GLOBUS_INSTALL_PATH)'
-exec_prefix='$(GLOBUS_INSTALL_PATH)'
+if test "x$GPT_LOCATION" = "x"; then
+    export GPT_LOCATION=$GLOBUS_LOCATION
+fi
+
+prefix='$(GLOBUS_LOCATION)'
+exec_prefix='$(GLOBUS_LOCATION)'
 
 dnl check for perl
 
@@ -95,11 +99,10 @@ AC_OUTPUT(Makefile
 	pkgdata/Makefile
 	pkgdata/pkg_data_src.gpt
 	,
-	$GLOBUS_INSTALL_PATH/sbin/gpt_generate_bin_pkg_data  \
+	$GPT_LOCATION/sbin/gpt_generate_bin_pkg_data  \
 	--flavor=$GLOBUS_FLAVOR_NAME "./pkgdata/pkg_data_src.gpt"
 	,
 	GLOBUS_FLAVOR_NAME=$GLOBUS_FLAVOR_NAME
-
 	)
 
 
