bootstrap with latest gpt

diff --git a/gsi/openssl_gpt/configure b/gsi/openssl_gpt/configure
--- a/gsi/openssl_gpt/configure
+++ b/gsi/openssl_gpt/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.4.2.10 .
+# From configure.in Revision: 1.4.2.11 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.50.
 #
@@ -13786,6 +13786,7 @@ fi
 	GPT_LIBS_TMP=$EXTERNAL_LIBS
 	GPT_EXTERNAL_LIBS="$GPT_EXTERNAL_LIBS $GPT_LIBS_TMP"
 	GPT_LIB_LINKS=" $GPT_LIB_LINKS $GPT_LIBS_TMP"
+	GPT_PGM_LINKS=" $GPT_PGM_LINKS $GPT_LIBS_TMP"
 
 if test ! -z "$INSURE"; then
 	CC=$INSURE
@@ -13874,7 +13875,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13877: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13878: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -14050,7 +14051,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:14053: error: ambiguous option: $1
+    { { echo "$as_me:14054: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -14137,12 +14138,12 @@ Try \`$0 --help' for more information." >&2;}
   'crypto/opensslconf.h' ) CONFIG_HEADERS="$CONFIG_HEADERS crypto/opensslconf.h:crypto/opensslconf.h.in" ;;
 
   # This is an error.
-  -*) { { echo "$as_me:14140: error: unrecognized option: $1
+  -*) { { echo "$as_me:14141: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
    { (exit 1); exit 1; }; } ;;
-  *) { { echo "$as_me:14145: error: invalid argument: $1" >&5
+  *) { { echo "$as_me:14146: error: invalid argument: $1" >&5
 echo "$as_me: error: invalid argument: $1" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -14459,7 +14460,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14462: creating $ac_file" >&5
+    { echo "$as_me:14463: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14477,7 +14478,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14480: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14481: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14490,7 +14491,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14493: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14494: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14551,7 +14552,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14554: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14555: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14562,7 +14563,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14565: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14566: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14575,7 +14576,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14578: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14579: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14692,7 +14693,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14695: $ac_file is unchanged" >&5
+      { echo "$as_me:14696: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
