added checks for CN=(null) and domain=localdomain

diff --git a/gsi/ssl_utils/source/programs/grid-cert-request b/gsi/ssl_utils/source/programs/grid-cert-request
--- a/gsi/ssl_utils/source/programs/grid-cert-request
+++ b/gsi/ssl_utils/source/programs/grid-cert-request
@@ -487,7 +487,7 @@ getUserCN () {
      fi
    fi
 
-   if [ -z "${_common_name}" ] ;  then
+   if [ -z "${_common_name}" ] || [ "${_common_name}" = "(null)" ];  then
       ${GLOBUS_SH_PRINTF-printf} "Enter your name, e.g., John Smith: " 1>&2
       read _common_name
    fi
@@ -742,6 +742,14 @@ readCommandLine "$@"
 
 # See if we can proceed
 . ${security_conf}
+
+if [ "${_domain}" = "localdomain" ]; then
+    echo
+    echo "ERROR: your domain name is currently set to: ${_domain}."
+    echo "       Please set it to a fully qualified domain based"
+    echo "       on your network configuration."
+    exit 1;
+fi
 
 # Set the actual file names
 
