updated scripts to work (mostly) with the new packaging stuff

diff --git a/gsi/ssl_utils/source/programs/grid-cert-info b/gsi/ssl_utils/source/programs/grid-cert-info
--- a/gsi/ssl_utils/source/programs/grid-cert-info
+++ b/gsi/ssl_utils/source/programs/grid-cert-info
@@ -1,11 +1,19 @@
-#! @SH@
+#!/bin/sh
 #
 # globus-cert-info
 #
 # Easily extract information from a user's cert.
 #
 
-@globus_script_initializer@
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
 
@@ -48,14 +56,14 @@ ${short_usage}
 EOF
 }
 
-@globus_args_parser_header@
+. $libexecdir/globus-args-parser-header
 
 
 #SSL related needs
-PATH=${GLOBUS_SSL_PATH}/bin:${PATH}
-SSLEAY="${GLOBUS_SSL_PATH}/bin/ssleay"
-if [ -r ${GLOBUS_SSL_PATH}/bin/openssl ]; then
-	SSLEAY="${GLOBUS_SSL_PATH}/bin/openssl"
+PATH=${GLOBUS_LOCATION}/bin:${PATH}
+SSLEAY="${GLOBUS_LOCATION}/bin/ssleay"
+if [ -r ${GLOBUS_LOCATION}/bin/openssl ]; then
+	SSLEAY="${GLOBUS_LOCATION}/bin/openssl"
 fi
 	
 
diff --git a/gsi/ssl_utils/source/programs/grid-cert-renew b/gsi/ssl_utils/source/programs/grid-cert-renew
--- a/gsi/ssl_utils/source/programs/grid-cert-renew
+++ b/gsi/ssl_utils/source/programs/grid-cert-renew
@@ -1,7 +1,14 @@
-#! @SH@
+#!/bin/sh
 
-# Inserted by configure.
-@globus_script_initializer@
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 
 #
 # renew a request using a Globus 1.0 or 1.1 installation
@@ -39,7 +46,7 @@ ${short_usage}
 EOF
 }
 
-@globus_args_parser_header@
+. $libexecdir/globus-args-parser-header
 
 
 MyWhich()
@@ -81,9 +88,9 @@ trap bailout 1 2 3 6 15
 #########################################################################
 # start
 
-sslexec=${GLOBUS_SSL_PATH}/bin/${ssl_exec_name}
-if [ -r ${GLOBUS_SSL_PATH}/bin/openssl ]; then
-	sslexec=${GLOBUS_SSL_PATH}/bin/openssl
+sslexec=${GLOBUS_LOCATION}/bin/${ssl_exec_name}
+if [ -r ${GLOBUS_LOCATION}/bin/openssl ]; then
+	sslexec=${GLOBUS_LOCATION}/bin/openssl
 	ssl_exec_name="openssl"
 fi
 proxy_init=${bindir}/grid-proxy-init
diff --git a/gsi/ssl_utils/source/programs/grid-cert-request.in b/gsi/ssl_utils/source/programs/grid-cert-request.in
--- a/gsi/ssl_utils/source/programs/grid-cert-request.in
+++ b/gsi/ssl_utils/source/programs/grid-cert-request.in
@@ -1,7 +1,15 @@
-#! @SH@
+#!/bin/sh
 
-# Inserted by configure.
-@globus_script_initializer@
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
+
 
 #
 # Sample script to generate a certificate request which can be sent 
@@ -36,16 +44,15 @@ ${short_usage}
 EOF
 }
 
-@globus_args_parser_header@
-
+. $libexecdir/globus-args-parser-header
 
 gssapi_authentication=@GSSAPI_TYPE@
 
 #SSL related needs
-PATH=${GLOBUS_SSL_PATH}/bin:${PATH}
-SSLEAY="${GLOBUS_SSL_PATH}/bin/ssleay"
-if [ -r ${GLOBUS_SSL_PATH}/bin/openssl ]; then
-    SSLEAY="${GLOBUS_SSL_PATH}/bin/openssl"
+PATH=${GLOBUS_LOCATION}/bin:${PATH}
+SSLEAY="${GLOBUS_LOCATION}/bin/ssleay"
+if [ -r ${GLOBUS_LOCATION}/bin/openssl ]; then
+    SSLEAY="${GLOBUS_LOCATION}/bin/openssl"
 fi
 SSLEAY_CONFIG="${sysconfdir}/globus-user-ssleay.conf"
 SSLEAY_USER_CONFIG="${sysconfdir}/globus-user-ssleay.conf"
diff --git a/gsi/ssl_utils/source/programs/grid-change-pass-phrase b/gsi/ssl_utils/source/programs/grid-change-pass-phrase
--- a/gsi/ssl_utils/source/programs/grid-change-pass-phrase
+++ b/gsi/ssl_utils/source/programs/grid-change-pass-phrase
@@ -1,9 +1,18 @@
-#! @SH@
+#!/bin/sh
 #
 # Change the pass phrase on a user's private key
 #
 
-@globus_script_initializer@
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
+
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} -e 's|.*/||g'`
 
@@ -30,9 +39,9 @@ ${short_usage}
 EOF
 }
 
-@globus_args_parser_header@
+. $libexecdir/globus-args-parser-header
 
-if [ -z "$GLOBUS_SSL_PATH" ]; then
+if [ -z "$GLOBUS_LOCATION" ]; then
    if [ ! -r ${sysconfdir}/globus-paths.sh ] ; then
       echo "ERROR: ${sysconfdir}/globus-paths.sh not found" >&2
       exit 1
@@ -41,10 +50,10 @@ if [ -z "$GLOBUS_SSL_PATH" ]; then
 fi
 
 # SSL related need
-PATH="${GLOBUS_SSL_PATH}/bin:${PATH}"
-SSLEAY=${GLOBUS_SSL_PATH}/bin/ssleay
-if [ -r ${GLOBUS_SSL_PATH}/bin/openssl ]; then
-    SSLEAY="${GLOBUS_SSL_PATH}/bin/openssl"
+PATH="${GLOBUS_LOCATION}/bin:${PATH}"
+SSLEAY=${GLOBUS_LOCATION}/bin/ssleay
+if [ -r ${GLOBUS_LOCATION}/bin/openssl ]; then
+    SSLEAY="${GLOBUS_LOCATION}/bin/openssl"
 fi
 
 
diff --git a/gsi/ssl_utils/source/programs/grid-security-config.in b/gsi/ssl_utils/source/programs/grid-security-config.in
--- a/gsi/ssl_utils/source/programs/grid-security-config.in
+++ b/gsi/ssl_utils/source/programs/grid-security-config.in
@@ -1,7 +1,14 @@
-#! @SH@
+#!/bin/sh
 
-# Inserted by configure.
-@globus_script_initializer@
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 
 
 trap '${GLOBUS_SH_RM-rm} -f ${TEMP_FILE1} ' 0
