Replace @GLOBUS_SCRIPT_INITIALIZER@

diff --git a/gram/jobmanager/scheduler_event_generator/source/init/globus-scheduler-event-generator-nolsb.in b/gram/jobmanager/scheduler_event_generator/source/init/globus-scheduler-event-generator-nolsb.in
--- a/gram/jobmanager/scheduler_event_generator/source/init/globus-scheduler-event-generator-nolsb.in
+++ b/gram/jobmanager/scheduler_event_generator/source/init/globus-scheduler-event-generator-nolsb.in
@@ -32,9 +32,25 @@
 # limitations under the License.
 #
 
-@GLOBUS_SCRIPT_INITIALIZER@
+prefix="${GLOBUS_LOCATION-@prefix@}"
+exec_prefix="@exec_prefix@"
+sbindir="@sbindir@"
+bindir="@bindir@"
+libdir="@libdir@"
+includedir="@includedir@"
+datarootdir="@datarootdir@"
+datadir="@datadir@"
+libexecdir="@libexecdir@"
+sysconfdir="@sysconfdir@"
+sharedstatedir="@sharedstatedir@"
+localstatedir="@localstatedir@"
 
-. ${libexecdir}/globus-script-initializer
+if [ -r ${libexecdir}/globus-script-initializer ]; then
+    . ${libexecdir}/globus-script-initializer
+else
+    echo "Unable to locate globus-script-initializer" 1>&2
+    exit 1
+fi
 
 progname=globus-scheduler-event-generator
 GLOBUS_SEG_CONFIG=${GLOBUS_SEG_CONFIG:-@SEG_CONFIGDIR@/@SEG_CONFIGFILE@}
