added source of security_conf file fix

diff --git a/gsi/simple_ca/setup/template/configure b/gsi/simple_ca/setup/template/configure
--- a/gsi/simple_ca/setup/template/configure
+++ b/gsi/simple_ca/setup/template/configure
@@ -1157,10 +1157,12 @@ fi
 
 
 
-# Extract the first word of "tar gtar", so it can be a program name with args.
-set dummy tar gtar; ac_word=$2
+for ac_prog in gnutar gtar tar
+do
+# Extract the first word of "$ac_prog", so it can be a program name with args.
+set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:1164: checking for $ac_word" >&5
+echo "configure:1166: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_TAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -1182,7 +1184,6 @@ else
     fi
   done
   IFS="$ac_save_ifs"
-  test -z "$ac_cv_path_TAR" && ac_cv_path_TAR="failed"
   ;;
 esac
 fi
@@ -1193,9 +1194,18 @@ else
   echo "$ac_t""no" 1>&6
 fi
 
+test -n "$TAR" && break
+done
+test -n "$TAR" || TAR="failed"
+
 
 if test $TAR = failed; then
-{ echo "configure: error: "Could not find gnu tar in your current path"" 1>&2; exit 1; }
+    { echo "configure: error: "Could not find gnu tar in your current path"" 1>&2; exit 1; }
+else
+    $TAR --version | grep "GNU" > /dev/null
+    if test $? -ne 0; then
+        { echo "configure: error: "Your version of tar is not GNU tar.  This package requires GNU tar to be installed on your system"" 1>&2; exit 1; }    
+    fi
 fi
 
 trap '' 1 2 15
