added some fixes

diff --git a/gsi/simple_ca/setup/template/grid-default-ca b/gsi/simple_ca/setup/template/grid-default-ca
--- a/gsi/simple_ca/setup/template/grid-default-ca
+++ b/gsi/simple_ca/setup/template/grid-default-ca
@@ -1,8 +1,19 @@
 #!/bin/sh
 
-interactive() {
+show_default() {
 
-    INSTALLED_CERTS="`echo $secconfdir/certificates/*.0`"
+    DEFAULTCACONFFILE=`${GLOBUS_SH_LS-ls} -l "$secconfdir/grid-security.conf" | ${GLOBUS_SH_SED-sed} -e "s|.*-> \(.*\)|\1|"`
+    DEFAULTCAHASH=`echo "$DEFAULTCACONFFILE" | ${GLOBUS_SH_SED-sed} -e "s|.*\.\(.*\)$|\1|"`
+    
+    echo
+    echo "The default CA is:  $DEFAULTCAHASH"
+    echo
+}
+
+ca_list() {
+
+
+    INSTALLED_CERTS="`echo $trusted_certs_dir/*.0`"
 
     if [ -z "${INSTALLED_CERTS}" ]; then
         echo "No CA's have been installed on this host!"
@@ -15,18 +26,34 @@ interactive() {
     fi
     
     index=1
-    for cert in $secconfdir/certificates/*.0; do
+    for cert in $trusted_certs_dir/*.0; do
     
         eval "CA${index}=${cert}"
         TEMP_SUBJECT=`openssl x509 -in ${cert} -noout -subject`
         eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
-        eval "echo \"$index)  \${CA_SUBJECT${index}}\""
+        TEMP_HASH=`echo ${cert} | ${GLOBUS_SH_SED-sed} -e  "s|.*/\([^/]*\)\.0|\1|"`
+        eval "CA_HASH${index}=$TEMP_HASH"
+        eval "echo \"$index) \${CA_HASH${index}} -  \${CA_SUBJECT${index}}\""
         index=$[ $index + 1 ]
     done
+
+    show_default
+}
+
+interactive() {
     
+    ca_list
+
     echo
     echo -n "Enter the index number of the CA to set as the default: "
     read CA_CHOSEN_INDEX
+
+    while [ -z "$CA_CHOSEN_INDEX" ]
+    do
+        echo
+        echo -n "Enter the index number of the CA to set as the default: "
+        read CA_CHOSEN_INDEX
+    done
     
     if [ $[ 0 < ${CA_CHOSEN_INDEX} ] == 0 ] ||
        [ $[ $index > ${CA_CHOSEN_INDEX} ] == 0 ]; then
@@ -37,6 +64,67 @@ interactive() {
     eval "CA_SUBJECT=\${CA_SUBJECT${CA_CHOSEN_INDEX}}"
     eval "CA_CERT=\${CA${CA_CHOSEN_INDEX}}"
 }
+
+readCommandLine () {
+    # Expects $* from the shell invocation
+
+    while [ "X$1" != "X" ]
+    do
+        case $1 in
+            -\?|-h|-help|usage)
+                long_usage
+                exit 0
+                ;;
+                
+            -dir)
+                secconfdir="$2"
+                shift ; shift
+                ;;
+
+            -list)
+                JUSTLIST=1
+                shift 
+                ;;
+            -ca)
+                ca_to_use="$2"
+                shift ; shift
+                ;;
+            *)
+                globus_args_unrecognized_option "$1"
+                ;;
+         esac
+    done
+
+}
+
+error() {
+
+    eval "missing_file=\$$1"
+
+    echo
+    echo "The file: ${missing_file} does not exist"
+    echo "The CA: ${CA_SUBJECT}"
+    echo "has not been setup correctly."
+    echo
+    exit 1
+}
+
+long_usage () {
+    ${GLOBUS_SH_CAT-cat} >&2 <<EOF
+
+${short_usage}
+
+    Options:
+      -help            : Display this message
+      -dir <dir_name>  : The security config directory (defaults to
+                         /etc/grid-security/)
+      -list            : List the available CAs to use and the current
+                         default
+      -ca <ca hash>    : Set the default CA non-interactively
+EOF
+
+}
+
 
 ############################################################
 # main code section
@@ -52,9 +140,17 @@ fi
 . ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 globus_source ${libexecdir}/globus-sh-tools.sh
 
+PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
+short_usage="$PROGRAM_NAME [-help] [ options ...]"
 
+. $libexecdir/globus-args-parser-header
 
-secconfdir=${GRID_SECURITY_DIR-/etc/grid-security/}
+readCommandLine "$@"
+
+if [ -z "$secconfdir" ]; then
+    secconfdir=${GRID_SECURITY_DIR-/etc/grid-security/}
+fi
+
 trusted_certs_dir=$secconfdir/certificates/
 
 if [ $secconfdir -ef "${GLOBUS_LOCATION}/etc/" ]; then
@@ -67,6 +163,11 @@ if [ ! -d "${secconfdir}" ] || [ ! -d "${trusted_certs_dir}" ]; then
     echo "Run ${GLOBUS_LOCATION}/setup/globus/setup-gsi"
     echo
     exit 1
+fi
+
+if [ -n "$JUSTLIST" ]; then
+    ca_list
+    exit
 fi
 
 if [ ! -w "${secconfdir}" ]; then
@@ -83,10 +184,10 @@ if [ ! -w "${secconfdir}" ]; then
     exit 1
 fi
 
-if [ -z $1 ]; then
+if [ -z "$ca_to_use" ]; then
     interactive
 else
-    CA_CERT=$1
+    CA_CERT="$ca_to_use"
     TMP_SUBJECT=`openssl x509 -in ${CA_CERT} -noout -subject`
     CA_SUBJECT=`echo ${TMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e "s|subject= ||"`
 fi
@@ -100,18 +201,6 @@ NEW_DEFAULT_CA_HASH=`openssl x509 -in ${CA_CERT} -noout -hash`
 GRID_SECURITY_FILE=${trusted_certs_dir}/grid-security.conf.${NEW_DEFAULT_CA_HASH}
 CA_SSL_HOST_CONFIG_FILE=${trusted_certs_dir}/globus-host-ssl.conf.${NEW_DEFAULT_CA_HASH}
 CA_SSL_USER_CONFIG_FILE=${trusted_certs_dir}/globus-user-ssl.conf.${NEW_DEFAULT_CA_HASH}
-
-error() {
-
-    eval "missing_file=\$$1"
-
-    echo
-    echo "The file: ${missing_file} does not exist"
-    echo "The CA: ${CA_SUBJECT}"
-    echo "has not been setup correctly."
-    echo
-    exit 1
-}
 
 
 if [ -w ${GRID_SECURITY_FILE} ]; then
