fixed some bugs - moved versions of source and setup to 0.4 - bundle release now at beta-r1

diff --git a/gsi/simple_ca/setup/setup-simple-ca b/gsi/simple_ca/setup/setup-simple-ca
--- a/gsi/simple_ca/setup/setup-simple-ca
+++ b/gsi/simple_ca/setup/setup-simple-ca
@@ -1,5 +1,21 @@
 #! /bin/sh
 
+# catch the kill signal (ctrl-c) and do cleanup
+trap do_trap 1 2 3 6 9 13 15
+
+if test "`echo -n \"testecho\"`" = "testecho"; then
+    ECHOOPTION=" -n "
+    ECHOTAIL=""
+else
+    ECHOOPTION=""
+    ECHOTAIL='\c'
+fi
+
+recho() {
+
+    echo $ECHOOPTION $@ $ECHOTAIL
+}
+
 ############################################################
 # grid-ca-setup: Set up the CA configuration
 ############################################################
@@ -14,6 +30,7 @@ make_template_ca_setup() {
     template_package_file=${template_package_dir}/globus_simple_ca_setup_template.tar.gz
     tmp_ca_setup_dir=${GLOBUS_SH_TMP-/tmp/}/${USER}_tmp_ca_setup
     ${GLOBUS_SH_MKDIR-mkdir} ${tmp_ca_setup_dir}
+    current_dir=${PWD}
     cd ${tmp_ca_setup_dir}
     
     ${GLOBUS_SH_GZIP-gzip} -dc ${template_package_file} | ${GLOBUS_SH_TAR-tar} xf -
@@ -49,14 +66,14 @@ grid_ca_conf=${GRID_CA_DIR}/grid-ca-ssl.conf
 if test -d "${GRID_CA_DIR}"; then
     echo ""
     echo "ERROR: It looks like a CA has already been setup at this location."
-    echo -n "Do you want to overwrite this CA? (y/n) [n]: "
+    recho "Do you want to overwrite this CA? (y/n) [n]: "
     read tmp_answer
     overwrite_answer=${tmp_answer:-n}
-    if test `echo ${overwrite_answer} | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z' | ${GLOBUS_SH_CUT-cut} -c1` != 'y'; then
+    if test ! `echo ${overwrite_answer} | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z' | ${GLOBUS_SH_CUT-cut} -c1` = 'y'; then
 	exit;
     fi
 else
-    if [ ! -d "${HOME}/.globus" ]; then
+    if test ! -d "${HOME}/.globus"; then
 	${GLOBUS_SH_MKDIR-mkdir} ${HOME}/.globus
     fi
     ${GLOBUS_SH_MKDIR-mkdir} ${GRID_CA_DIR}
@@ -95,11 +112,11 @@ generate_unique_name() {
 
 tmp_hostname=`${GLOBUS_LOCATION}/bin/globus-hostname`
 
-if [ -z "${tmp_hostname}" ]; then
-    echo 
+if test -z "${tmp_hostname}"; then
+    echo "" 
     echo "The hostname of this machine is not set.  Set the"
     echo "hostname before running this script."
-    echo
+    echo ""
     exit 1
 fi
 
@@ -119,31 +136,31 @@ GSI_CA_BASE_DN="ou=${CA_ORG_NAME}, ou=GlobusTest, o=Grid"
 GSI_CA_NAME="Globus Simple CA"
 
 got_subject=""
-while [ -z "${got_subject}" ]; do
+while test -z "${got_subject}" ; do
 
     casubject="cn=${GSI_CA_NAME}, ${GSI_CA_BASE_DN}"
 	
-    echo 
+    echo ""
     echo "The unique subject name for this CA is:"
-    echo
+    echo ""
     echo "${casubject}"
-    echo
-    echo -n "Do you want to keep this as the CA subject (y/n) [y]: "
+    echo ""
+    recho "Do you want to keep this as the CA subject (y/n) [y]: "
 
     read _answer
     answer=${_answer:-y}
 
-    if [ "`echo ${answer} | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z' | ${GLOBUS_SH_CUT-cut} -c1`" == 'n' ]; then
+    if test "`echo ${answer} | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z' | ${GLOBUS_SH_CUT-cut} -c1`" = 'n'; then
     
-	echo 
-	echo -n "Enter a unique subject name for this CA: "
+	echo ""
+	recho "Enter a unique subject name for this CA: "
 	read casubject
-	echo
-	if [ ! -z "${casubject}" ]; then
+	echo ""
+	if test -n "${casubject}"; then
 	    GSI_CA_NAME=`echo ${casubject} | ${GLOBUS_SH_SED-sed} -e "s/cn=\([^,]*\),.*/\1/"`
 	    GSI_CA_BASE_DN=`echo ${casubject} | ${GLOBUS_SH_SED-sed} -e "s/cn=[^,]*,\(.*\)/\1/"`
-	    if [ -z "${GSI_CA_NAME}" ] || [ -z "${GSI_CA_BASE_DN}" ]; then
-		echo 
+	    if test -z "${GSI_CA_NAME}" || test -z "${GSI_CA_BASE_DN}"; then
+		echo "" 
 		echo "The subject: ${casubject} is not a valid subject name"
 		echo "Use the default subject name if you don't know the correct"
 		echo "format to use"
@@ -158,13 +175,13 @@ while [ -z "${got_subject}" ]; do
 done
 
 get_ca_email=""
-while [ -z ${get_ca_email} ]; do
+while test -z "${get_ca_email}"; do
 
-    echo 
+    echo ""
     echo "Enter the email of the CA (this is the email where certificate"
-    echo -n "requests will be sent to be signed by the CA): "
+    recho "requests will be sent to be signed by the CA): "
     read GSI_CA_EMAIL_ADDR
-    if [ ! -z ${GSI_CA_EMAIL_ADDR} ]; then
+    if test -n ${GSI_CA_EMAIL_ADDR}; then
 	get_ca_email="done"
     fi
 done
@@ -180,7 +197,7 @@ by re-running this setup script.  Enter the number of DAYS
 the CA certificate should last before it expires.
 EOF
 
-echo -n "[default: 5 years (1825 days)]: "
+recho "[default: 5 years (1825 days)]: "
 read _CA_CERT_DAYS
 CA_CERT_DAYS=${_CA_CERT_DAYS:-${CA_CERT_DAYS}}
 echo
@@ -348,7 +365,7 @@ RET=$?
 
 ${GLOBUS_SH_RM-rm} -f ${CA_REQ_INPUT}
 
-if [ ${RET} -eq 0 ] ; then
+if test ${RET} -eq 0; then
     ${GLOBUS_SH_CLEAR-clear}
 else
     echo "Error number ${RET} was returned by " 1>&2
@@ -389,15 +406,37 @@ ${GRID_CA_DIR}/${CA_UTILS_PACKAGE}
 This file must be distributed to any host wishing to request
 certificates from this CA.
 
-To install this package, run:
+CA setup complete.
+
+The following commands will now be run to setup the security
+configuration files for this CA:
 
 \$GLOBUS_LOCATION/sbin/globus-build -install-only \\
 ${GRID_CA_DIR}/${CA_UTILS_PACKAGE}
 
-CA setup complete.
+\$GLOBUS_LOCATION/setup/globus-postinstall.sh
+
+-------------------------------------------------------------------
+
 
 EOF
 
+}
+
+############################################################
+# install_security_config: run globus-build on the security
+#                          configuration package associated
+#                          with the CA
+#
+############################################################
+install_security_config() {
+
+    cd ${current_dir}
+
+    ${GLOBUS_LOCATION}/sbin/globus-build -install-only \
+    ${GRID_CA_DIR}/${CA_UTILS_PACKAGE}
+
+    ${GLOBUS_LOCATION}/setup/globus-postinstall.sh
 }
 
 ############################################################
@@ -459,8 +498,8 @@ generate_setup_file "Makefile.in"
 generate_setup_file "/pkgdata/pkg_data_src.gpt.in"
 ${GLOBUS_SH_CP-cp} "${tmp_ca_setup_dir}/globus-ssl.conf.tmpl" "${tmp_ca_setup_dir}/globus-ssl.conf"
 
-echo
-echo -n "creating CA config package..."
+echo ""
+recho "creating CA config package..."
 
 cd ${tmp_ca_setup_dir}
 
@@ -473,7 +512,7 @@ make dist
 
 CA_UTILS_PACKAGE=globus_simple_ca_${CA_CERT_HASH}_setup-0.3.tar.gz
 
-if [ ! -f ${tmp_ca_setup_dir}/${CA_UTILS_PACKAGE} ]; then
+if test ! -f ${tmp_ca_setup_dir}/${CA_UTILS_PACKAGE}; then
     echo ""
     echo "Building the CA package failed."
     echo ""
@@ -488,6 +527,27 @@ ${GLOBUS_SH_RM-rm} -rf ${tmp_ca_setup_dir}
 echo "done."
 echo
 
+}
+
+############################################################
+# do_trap:  catches any abortive signals and does cleanup
+############################################################
+do_trap() {
+
+    echo ""
+    echo "Normal program execution interrupted.  You will"
+    echo "need to rerun the script:"
+    echo ""
+    echo "\${GLOBUS_LOCATION}/setup/globus/setup-simple-ca"
+    echo ""
+    echo "to setup the simple CA."
+    echo ""
+
+    ${GLOBUS_SH_RM-rm} -rf ${tmp_ca_setup_dir}
+
+    cd ${current_dir}
+    
+    exit 1
 }
 
 
@@ -524,5 +584,7 @@ save_ca_settings
 generate_ca_certificate
 generate_utils_package
 emit_directions
+install_security_config
+
 
 exit
diff --git a/gsi/simple_ca/source/grid-ca-sign b/gsi/simple_ca/source/grid-ca-sign
--- a/gsi/simple_ca/source/grid-ca-sign
+++ b/gsi/simple_ca/source/grid-ca-sign
@@ -1,23 +1,30 @@
 #! /bin/sh
 
+# catch the kill signal (ctrl-c) and do cleanup
+trap do_trap 1 2 3 6 9 13 15
+
+if test "`echo -n \"testecho\"`" = "testecho"; then
+    ECHOOPTION=" -n "
+    ECHOTAIL=""
+else
+    ECHOOPTION=""
+    ECHOTAIL='\c'
+fi
+
 recho() {
 
-    if [ "$1" = "-n" ]; then
-        echo -n "$2" 1>&2
-    else
-        echo $1 1>&2
-    fi
+    echo $ECHOOPTION $@ $ECHOTAIL
 }
 
 ############################################################
 # main code section
 ############################################################
 if test -z "${GLOBUS_LOCATION}"; then
-    recho ""
-    recho "ERROR: Please set GLOBUS_LOCATION to the" 
-    recho "Globus installation directory before"
-    recho "running this script"
-    recho ""
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the" 
+    echo "Globus installation directory before"
+    echo "running this script"
+    echo ""
     exit 1
 fi
 
@@ -51,7 +58,7 @@ EOF
 
 readCommandLine() {
 
-    while [ ! -z "$1" ] 
+    while test -n "$1" 
     do
         case $1 in
             -\?|-h|-help|-usage)
@@ -84,39 +91,56 @@ readCommandLine() {
         esac
     done
     
-    if [ -z "$INPUT_REQ_FILE" ]; then
-        recho ""
-        recho "ERROR: Please specify a request file using the -in option"
-        recho ""
+    if test -z "$INPUT_REQ_FILE"; then
+        echo ""
+        echo "ERROR: Please specify a request file using the -in option"
+        echo ""
         exit 1
     else
-        if [ ! -r ${INPUT_REQ_FILE} ]; then
-            recho ""
-            recho "ERROR: The file: ${INPUT_REQ_FILE} is not readable"
-            recho ""
+        if test ! -r ${INPUT_REQ_FILE}; then
+            echo ""
+            echo "ERROR: The file: ${INPUT_REQ_FILE} is not readable"
+            echo ""
             exit 1
         fi
     fi
 
-    if [ -z "$SIGNED_OUTPUT_FILE" ]; then
-        recho ""
-        recho "ERROR: Please specify a output file using the -out option"
-        recho ""
+    if test -z "$SIGNED_OUTPUT_FILE"; then
+        echo ""
+        echo "ERROR: Please specify a output file using the -out option"
+        echo ""
         exit 1
     fi
 }
 
+do_trap() {
+
+    echo ""
+    echo "Normal program execution interrupted.  Exiting."
+    echo ""
+    do_cleanup
+    exit 1
+}
+
+do_cleanup() {
+
+    ${GLOBUS_SH_RM-rm} -f ${tmp_input_file}
+    ${GLOBUS_SH_RM-rm} -f ${tmp_output}
+
+    ${GLOBUS_SH_RM-rm} -f ${TMP_REQ_FILE} ${TMP_CERT_FILE}
+}
+
 readCommandLine "$@"
 
-if [ -z "$GRID_CA_DIR" ]; then
+if test -z "$GRID_CA_DIR"; then
     GRID_CA_DIR=${HOME}/.globus/simpleCA/
 fi
 
-if [ ! -f ${GRID_CA_DIR}/cacert.pem ]; then
-    recho ""
-    recho "No simple CA directory found.  Run setup-simple-ca before"
-    recho "signing certificates."
-    recho ""
+if test ! -f ${GRID_CA_DIR}/cacert.pem; then
+    echo ""
+    echo "No simple CA directory found.  Run setup-simple-ca before"
+    echo "signing certificates."
+    echo ""
     exit 1
 fi
 
@@ -126,15 +150,14 @@ openssl_cmd=${GLOBUS_LOCATION}/bin/openssl
 TMP_REQ_FILE=/tmp/tmp_cert_req.pem.$$
 TMP_CERT_FILE=/tmp/tmp_cert.pem.$$
 
-
 ${GLOBUS_SH_CP-cp} ${INPUT_REQ_FILE} ${TMP_REQ_FILE}
 
-recho ""
-recho -n "Enter password for the CA key: "
+echo ""
+recho "Enter password for the CA key: "
 ${GLOBUS_SH_STTY-stty} -echo
 read password 0<&2
 ${GLOBUS_SH_STTY-stty} echo
-recho ""
+echo ""
 tmp_input_file=/tmp/tmp_input.$$
 echo "y
 y
@@ -145,95 +168,130 @@ ${openssl_cmd} ca -config ${grid_ca_conf} -key "${password}" \
                   -in ${TMP_REQ_FILE} -out ${TMP_CERT_FILE} \
                   < $tmp_input_file 2> $tmp_output 
 
+openssl_result=$?
+
 SIGNED_SERIAL=`cat ${tmp_output} | ${GLOBUS_SH_GREP-grep} "Serial Number" | \
                ${GLOBUS_SH_SED-sed} -e "s/Serial Number ://"`
 
-no_config_file=`${GLOBUS_SH_GREP-grep} "error loading the config file" ${tmp_output}`
-if [ ! -z "${no_config_file}" ]; then
+# check to see if an error occurred while signing
+if test "${openssl_result}" = "1"; then
 
-    recho ""
-    recho "ERROR: No CA config file found."
-    recho "the simple CA setup package must be installed."
-    recho ""
-    exit 1
-fi
+    echo ""
+    echo "========== ERROR MESSAGES FROM OPENSSL =========="
+    cat ${tmp_output} 1>&2
+    echo "================================================="
 
-wrong_password=`${GLOBUS_SH_GREP-grep} "unable to load CA private key" ${tmp_output}`
-if [ ! -z "${wrong_password}" ]; then
-    
-    recho ""
-    recho "ERROR: The CA private key could not be loaded."
-    recho "Possibly an incorrect password for the CA key was used."
-    recho ""
-    exit 1
-fi
+    # check if the error was with 
+    no_config_file=`${GLOBUS_SH_GREP-grep} "error loading the config file" ${tmp_output}`
+    if test -n "${no_config_file}"; then
 
-already_signed=`${GLOBUS_SH_GREP-grep} "ERROR:There is already a certificate" \
-                                       ${tmp_output}`
-
-if [ ! -z "${already_signed}" ]; then
-
-    SIGNED_EXP_DATE=`cat ${tmp_output} | ${GLOBUS_SH_GREP-grep} "Expires on" | \
-                     ${GLOBUS_SH_SED-sed} -e "s|Expires on[^:]*:\(.\{6\}\).*|\1|"`
-    TZ="GMT"   
-    export TZ
-    CURRENT_DATE=`date +%y%m%d`
-    
-    if [ ${SIGNED_EXP_DATE} -lt ${CURRENT_DATE} ] || [ ! -z "${force_sign}" ]; then
-
-        recho ""
-        recho "Revoking previous certificate"
-
-        tmp_revoke_output=/tmp/tmp_revoke_out.$$
-
-        ${openssl_cmd} ca -config ${grid_ca_conf} -key "${password}" \
-                          -revoke ${GRID_CA_DIR}/newcerts/${SIGNED_SERIAL}.pem \
-                          < $tmp_input_file 2> ${tmp_revoke_output}
-        
-        ${GLOBUS_SH_RM-rm} -f ${tmp_revoke_output}
-
-        recho "Signing new certificate"
-
-        ${openssl_cmd} ca -config ${grid_ca_conf} -key "${password}" \
-                          -in ${TMP_REQ_FILE} -out ${TMP_CERT_FILE} \
-                          < $tmp_input_file 2> $tmp_output
-
-    else
-        recho ""
-        recho "========== ERROR MESSAGES FROM OPENSSL =========="
-        cat ${tmp_output} 1>&2
-        recho "================================================="
-        recho 
-        recho "There is already a valid certificate that matches this subject at:"
-        recho
-        recho "${GRID_CA_DIR}/newcerts/${SIGNED_SERIAL}.pem"
-        recho
-        recho "You can use the -force option to overwrite"
-        recho "this certificate and create a new one."
-        recho ""
-
-        ${GLOBUS_SH_RM-rm} -f ${tmp_input_file}
-        ${GLOBUS_SH_RM-rm} -f ${tmp_output}
-
+        echo ""
+        echo "ERROR: No CA config file found."
+        echo "Either simple CA setup package is not installed,"
+        echo "or the config file is not located at:"
+        echo ""
+        echo "  ${grid_ca_conf}"
+        echo ""
+        do_cleanup
         exit 1
     fi
 
+    # check if the CA's private key could be loaded
+    wrong_password=`${GLOBUS_SH_GREP-grep} "unable to load CA private key" ${tmp_output}`
+    if test -n "${wrong_password}"; then
+    
+        echo ""
+        echo "ERROR: The CA private key could not be loaded."
+        echo "Possibly an incorrect password for the CA key was used."
+        echo ""
+        do_cleanup
+        exit 1
+    fi
+
+    # check that a certificate with the same subject has not
+    # already been signed
+    already_signed=`${GLOBUS_SH_GREP-grep} "ERROR:There is already a certificate" \
+                                       ${tmp_output}`
+    if test -n "${already_signed}"; then
+
+        SIGNED_EXP_DATE=`cat ${tmp_output} | ${GLOBUS_SH_GREP-grep} "Expires on" | \
+                     ${GLOBUS_SH_SED-sed} -e "s|Expires on[^:]*:\(.\{6\}\).*|\1|"`
+        TZ="GMT"   
+        export TZ
+        CURRENT_DATE=`date +%y%m%d`
+    
+        if test "${SIGNED_EXP_DATE}" -lt "${CURRENT_DATE}" || test -n "${force_sign}"; then
+
+            echo ""
+            echo "Revoking previous certificate"
+
+            tmp_revoke_output=/tmp/tmp_revoke_out.$$
+
+            ${openssl_cmd} ca -config ${grid_ca_conf} -key "${password}" \
+                    -revoke ${GRID_CA_DIR}/newcerts/${SIGNED_SERIAL}.pem \
+                          < $tmp_input_file 2> ${tmp_revoke_output}
+        
+            ${GLOBUS_SH_RM-rm} -f ${tmp_revoke_output}
+
+            echo "Signing new certificate"
+
+            ${openssl_cmd} ca -config ${grid_ca_conf} -key "${password}" \
+                          -in ${TMP_REQ_FILE} -out ${TMP_CERT_FILE} \
+                          < $tmp_input_file 2> $tmp_output
+
+        else
+            echo ""
+            echo "There is already a valid certificate that matches this subject at:"
+            echo
+            echo "${GRID_CA_DIR}/newcerts/${SIGNED_SERIAL}.pem"
+            echo
+            echo "You can use the -force option to overwrite"
+            echo "this certificate and create a new one."
+            echo ""
+
+            ${GLOBUS_SH_RM-rm} -f ${tmp_input_file}
+            ${GLOBUS_SH_RM-rm} -f ${tmp_output}
+
+            do_cleanup
+            exit 1
+        fi
+    fi
+
+    # check that the cert request matches the CA cert
+    wrong_org=`${GLOBUS_SH_GREP-grep} "field needed to be the same" ${tmp_output}`
+    if test -n "${wrong_org}"; then
+    
+        echo "" 
+        echo "ERROR: The cert request does not match CA cert"
+        echo "Check that the correct security config files are"
+        echo "set during grid-cert-request"
+        echo "correct security configuration is being used when"
+        echo "the certificate is being requested."
+        echo ""
+        echo "The default configuration can be set using either"
+        echo "the command:  grid-default-ca, or via the -ca option"
+        echo "to grid-cert-request."
+        echo ""
+        do_cleanup
+        exit 1
+    fi
+
+    echo ""
+    do_cleanup
+    exit 1
 fi
 
 NEW_SERIAL=`${openssl_cmd} x509 -in ${TMP_CERT_FILE} -noout -serial | ${GLOBUS_SH_SED-sed} -e "s|serial=||"`
 
-recho ""
-recho "The new signed certificate is at: ${GRID_CA_DIR}/newcerts/${NEW_SERIAL}.pem"
-recho ""
+echo ""
+echo "The new signed certificate is at: ${GRID_CA_DIR}/newcerts/${NEW_SERIAL}.pem"
+echo ""
+    
+CERT_OUTPUT_DIR="`echo ${SIGNED_OUTPUT_FILE} | ${GLOBUS_SH_SED-sed} -e \"s|\(.*\)/.*|\1|\"`"
 
-${GLOBUS_SH_RM-rm} -f ${tmp_input_file}
-${GLOBUS_SH_RM-rm} -f ${tmp_output}
-
-CERT_OUTPUT_DIR="`echo $SIGNED_OUTPUT_FILE | ${GLOBUS_SH_SED-sed} -e "s|\(.*\)/.*|\1|"`"
-
-if [ -w ${CERT_OUTPUT_DIR} ]; then
+if test -w "${CERT_OUTPUT_DIR}"; then
     ${GLOBUS_SH_CP-cp} ${TMP_CERT_FILE} ${SIGNED_OUTPUT_FILE}
 fi
 
-${GLOBUS_SH_RM-rm} -f ${TMP_REQ_FILE} ${TMP_CERT_FILE}
-
+do_cleanup
+exit
