added check to be backward compatible with beta stuff

diff --git a/gsi/simple_ca/setup/setup-simple-ca b/gsi/simple_ca/setup/setup-simple-ca
--- a/gsi/simple_ca/setup/setup-simple-ca
+++ b/gsi/simple_ca/setup/setup-simple-ca
@@ -12,15 +12,13 @@ make_template_ca_setup() {
 
     template_package_dir=${GLOBUS_LOCATION}/setup/globus/
     template_package_file=${template_package_dir}/globus_simple_ca_setup_template.tar.gz
-    tmp_ca_setup_dir=${GLOBUS_SH_TMP-/tmp/}/tmp_ca_setup/
-    echo "dir is: ${tmp_ca_setup_dir}"
+    tmp_ca_setup_dir=${GLOBUS_SH_TMP-/tmp/}/${USER}_tmp_ca_setup
     ${GLOBUS_SH_MKDIR-mkdir} ${tmp_ca_setup_dir}
     cd ${tmp_ca_setup_dir}
     
     ${GLOBUS_SH_GZIP-gzip} -dc ${template_package_file} | ${GLOBUS_SH_TAR-tar} xf -
 
     grid_security_conf_template=${tmp_ca_setup_dir}/grid-security.conf.tmpl
-    echo "file here is: ${grid_security_conf_template}"
     ca_signing_policy_conf_template=${tmp_ca_setup_dir}/ca-signing-policy.conf.tmpl
     ssl_conf_template=${tmp_ca_setup_dir}/globus-ssl.conf.tmpl
 }
@@ -211,7 +209,6 @@ save_ca_settings() {
     GSI_HOST_BASE_DN=${GSI_CA_BASE_DN}
     
 #    echo `cat ${security_conf_file} | env_replace SETUP GSI_CA_BASE_DN`
-    echo "file is: ${grid_security_conf_template}"
     ${GLOBUS_SH_CAT-cat} ${grid_security_conf_template}  |\
     env_replace SETUP   GSI_CA_BASE_DN    |\
     env_replace SETUP   GSI_CA_NAME       |\
@@ -463,11 +460,19 @@ ${GLOBUS_SH_CHMOD-chmod} 0700 configure
 ./configure
 make dist
 
-CA_UTILS_PACKAGE=globus_simple_ca_${CA_CERT_HASH}_setup-1.0.tar.gz
+CA_UTILS_PACKAGE=globus_simple_ca_${CA_CERT_HASH}_setup-0.1.tar.gz
+
+if [ ! -f ${tmp_ca_setup_dir}/${CA_UTILS_PACKAGE} ]; then
+    echo ""
+    echo "Building the CA package failed."
+    echo ""
+    exit 1;
+fi
+
 # versions of this generated package should not be changed ever
 ${GLOBUS_SH_CP-cp} ${tmp_ca_setup_dir}/${CA_UTILS_PACKAGE} ${GRID_CA_DIR}/${CA_UTILS_PACKAGE}
 
-#${GLOBUS_SH_RM-rm} -rf ${tmp_ca_setup_dir}
+${GLOBUS_SH_RM-rm} -rf ${tmp_ca_setup_dir}
 
 echo "done."
 echo
