removed check for gnu tar in configure.in.

diff --git a/gsi/simple_ca/setup/setup-simple-ca b/gsi/simple_ca/setup/setup-simple-ca
--- a/gsi/simple_ca/setup/setup-simple-ca
+++ b/gsi/simple_ca/setup/setup-simple-ca
@@ -616,23 +616,22 @@ CA_UTILS_PACKAGE=$CA_UTILS_PACKAGE_DIR.tar.gz
 #./bootstrap
 ./configure
 make distdir
-${GLOBUS_SH_CHMOD-chmod} -R a+r $(CA_UTILS_PACKAGE_DIR)
-tar
-if [ $? -eq 127 ]; then
+${GLOBUS_SH_CHMOD-chmod} -R a+r ${CA_UTILS_PACKAGE_DIR}
+${GLOBUS_SH_TAR-tar} cvf $CA_UTILS_PACKAGE_DIR.tar $CA_UTILS_PACKAGE_DIR
+if test $? -ne 0; then 
 	echo ""
-	echo "BUILD FAILED: tar does not appear to be in your path."
-	echo ""
-	exit 1;
-fi
-tar cvf $CA_UTILS_PACKAGE_DIR.tar $CA_UTILS_PACKAGE_DIR
-gzip
-if [ $? -eq 127 ]; then
-	echo ""
-	echo "BUILD FAILED: gzip does not appear to be in your path."
+	echo "SETUP FAILED: Could not create tarball of setup package."
 	echo ""
 	exit 1;
 fi
-gzip $CA_UTILS_PACKAGE_DIR.tar
+
+${GLOBUS_SH_GZIP-gzip} -f9 $CA_UTILS_PACKAGE_DIR.tar
+if test $? -ne 0; then
+	echo ""
+	echo "SETUP FAILED: Could not create gzip of setup package."
+	echo ""
+	exit 1;
+fi
 
 if test ! -f ${tmp_ca_setup_dir}/${CA_UTILS_PACKAGE}; then
     echo ""
