o Bug fix to make the script more stable and to update PID_FILE.

diff --git a/gssapi-openssh/setup/SXXsshd.in b/gssapi-openssh/setup/SXXsshd.in
--- a/gssapi-openssh/setup/SXXsshd.in
+++ b/gssapi-openssh/setup/SXXsshd.in
@@ -5,31 +5,36 @@ export GLOBUS_LOCATION
 
 . ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 . ${libexecdir}/globus-sh-tools.sh
-. ${sysconfdir}/grid-info.conf
 
 PID_FILE=${localstatedir}/sshd.pid
 
 case "$1" in
-  start)
-    echo "Starting up GSI-OpenSSH sshd server"
-    ${sbindir}/sshd &
-    if [ $? -ne 0 ] ; then
-      echo "Failed to start up GSI-OpenSSH sshd server"
-    fi
-    ;;
+    start)
+        if [ ! -f $PID_FILE ]; then
+            echo "Starting up GSI-OpenSSH sshd server"
+            ${sbindir}/sshd &
+            if [ $? -ne 0 ] ; then
+                echo "Failed to start up GSI-OpenSSH sshd server"
+            else
+                echo $! > $PID_FILE
+            fi
+        else
+            echo "GSI-OpenSSH sshd is already running..."
+        fi
+        ;;
 
-  stop)
-    if [ -f $PID_FILE ] ; then
-      kill -TERM `cat $PID_FILE`
-      sleep 2
-      kill -TERM `cat $PID_FILE` 2> /dev/null
-      rm -f $PID_FILE
-    fi
-    ;;
+    stop)
+        if [ -f $PID_FILE ] ; then
+            kill -TERM `cat $PID_FILE`
+            sleep 2
+            kill -TERM `cat $PID_FILE` 2> /dev/null
+            rm -f $PID_FILE
+        fi
+        ;;
 
   *)
-    echo "Usage: $0 ( start | stop )"
-    exit 1
+        echo "Usage: $0 ( start | stop )"
+        exit 1
 esac
 
 exit 0
