Merge from 5.0 branch: GRAM-53: Generalize log path configuration - New command-line option: -log-pattern PATTERN     Creates logs in files named by pattern. The previous -stdio-log DIRECTORY     option is equivalent to -log-pattern $(HOME)/gram_$(DATE).log
GRAM-207: Add RSL attribute to control the log level per job
- New RSL attribute "log_level"
    Override the default log level for this job. The value of this attribute
    consists of a combination of the strings FATAL, ERROR, WARN, INFO, DEBUG,
    TRACE joined by the | character. For example
    adding (log_level = ERROR|FATAL|WARN|INFO) to an RSL description will
    enable logging for those levels.

Note that this will only create a log file if logging is enabled globally
(by -stdio-log or -log-pattern in the configuration file), or if the
log_pattern RSL attribute described below is included in the RSL.

GRAM-208: Add RSL attribute to enable a log file created for an individual job
- New RSL attribute "log_pattern"
    Override the default log path pattern for this job. The value of this
    attribute is a string (potentially containing RSL substitutions) that is
    evaluated to the path to write the log to.  If the resulting string
    contains the string $(DATE) (or any other RSL substitution), it will be
    reevaluated at log time.

- New RSL substitution GLOBUS_GRAM_JOB_ID that can be used to store log data
  in a unique per-job log file.

diff --git a/gram/jobmanager/source/globus-personal-gatekeeper.in b/gram/jobmanager/source/globus-personal-gatekeeper.in
--- a/gram/jobmanager/source/globus-personal-gatekeeper.in
+++ b/gram/jobmanager/source/globus-personal-gatekeeper.in
@@ -463,6 +463,52 @@ else
   globus_toolkit_version="Unknown"
 fi
 
+if test "${jmtype}" = condor; then
+    found_condor_arch=0
+    found_condor_os=0
+    set -- ${startargs}
+    while [ $# -gt 0 ]; do
+        if [ "$1" = "-condor-arch" ]; then
+            found_condor_arch=1
+            shift
+        elif [ "$1" = "-condor-os" ]; then
+            found_condor_os=1
+            shift
+        fi
+        shift
+    done
+
+    if [ $found_condor_arch = 0 -o $found_condor_os = 0 ]; then
+        setupdir="${GLOBUS_LOCATION}/setup/globus"
+        if [ -x "${setupdir}/globus-condor-print-config" ]; then
+            set -- `${setupdir}/globus-condor-print-config` 
+            while [ $# -gt 0 ]; do
+                case $1 in
+                  -condor-arch)
+                      shift
+                      if [ $found_condor_arch = 0 ]; then
+                          startargs="$startargs -condor-arch $1"
+                          found_condor_arch=1
+                      fi
+                  ;;
+                  -condor-os)
+                      shift
+                      if [ $found_condor_os = 0 ]; then
+                          startargs="$startargs -condor-os $1"
+                          found_condor_os=1
+                      fi
+                  ;;
+                esac
+                shift
+            done
+        else
+            printf "Unable to determine -condor-os and/or condor-arch\n" 1>&2
+            docleanup=true
+            exit 1
+        fi
+    fi
+fi
+
 ${GLOBUS_SH_CAT-cat} > ${scratch}/jobmanager.conf <<EOF
 -home ${GLOBUS_LOCATION:-@exec_prefix@}
 -type ${jmtype}
