disabled using crypto libs besides openssl changed bootstrap to install globus_automake_pre even when NOP on the autotools

diff --git a/gsi/xmlsec1/bootstrap b/gsi/xmlsec1/bootstrap
--- a/gsi/xmlsec1/bootstrap
+++ b/gsi/xmlsec1/bootstrap
@@ -7,10 +7,27 @@ if test "x$GLOBUS_LOCATION" = "x"; then
     exit 1
 fi
 
+# install globus_automake_pre even if we're not goint to really bootstrap
+
+
+for file in 'globus_automake_pre' \
+    'globus_automake_post' \
+    'globus_automake_pre_top' \
+    'globus_automake_post_top'
+do
+    if test ! -f "${file}" ; then
+        if test -h "${file}" ; then
+            rm ${file}
+        fi
+        echo "installing ${file} link"
+        ln -s $GLOBUS_LOCATION/share/globus_aclocal/${file} ${file}
+    fi
+done
+
 automake_version=`automake --version | grep "automake (GNU automake) 1.6.3"`
 #
 if test "x$automake_version" = "x"; then
-    echo "You are not using automake 1.6.3.  Automake 1.6.3 and libtool 1.4.3 are required to re-eootstrap this package." >&2
+    echo "You are not using automake 1.6.3.  Automake 1.6.3 and libtool 1.4.3 are required to re-bootstrap this package." >&2
     exit 0
 fi
 
