unified globus-hostname and globus-domainname \ created a globus-localdomain.conf file so sites can EASILY modify the domainname after install

diff --git a/common/setup/globus-hostname.in b/common/setup/globus-hostname.in
--- a/common/setup/globus-hostname.in
+++ b/common/setup/globus-hostname.in
@@ -2,7 +2,8 @@
 
 # This is a simple shell script that acts like 
 # the hostname command.  But is returns the FQN
-# in all cases.
+# in all cases.  It also servers to return just the
+# domainname
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} -e 's|.*/||g'`
 PROGRAM_VERSION=`echo '$Revision$' | ${GLOBUS_SH_CUT-cut} -d' ' -f2`
@@ -15,12 +16,28 @@ long_usage()
 
 ${short_usage}
 
-    globus-hostname returns the system hostname and makes some
-    additional checks to ensure a fully qualified hostname.
+EOF
+  case "${PROGRAM_NAME}" in
 
+    globus-hostname)
+      echo ${PROGRAM_NAME} returns the system hostname and makes some 1>&2
+      echo additional checks to ensure a fully qualified hostname. 1>&2
+      ;;
+
+    globus-domainname)
+      ${PROGRAM_NAME} tries to return the system domainname 
+      ;;
+
+    *)
+      echo "Configuration error"  1>&2
+      exit 1
+      ;;
+    esac
+
+${GLOBUS_SH_CAT-cat} 1>&2 <<EOF
     Setting the environment variable GLOBUS_HOSTNAME will cause
-    globus-hostname to return that value instead. This is useful for
-    specifying the use of certain network interfaces when
+    ${PROGRAM_NAME} to return a valule based on this variable.
+    This is useful for specifying the use of certain network interfaces when
     communicating etc.
 
 EOF
@@ -33,36 +50,49 @@ EOF
 if [ -n "$1" ]; then
     globus_args_unrecognized_option "$1"
 fi
- 
-globus_hostname=""		# Replaced by deploy
 
-if [ -n "${globus_hostname}" ]; then
-    echo "${globus_hostname}"
-    exit 0
-fi
+globus_source ${sysconfdir}/globus-localdomain.conf
+ 
+_hostname="${GLOBUS_HOSTNAME}"
+_domainname="`echo ${_hostname}|${GLOBUS_SH_CUT-cut} -s -d '.' -f '2-'`"
 
-LOCALDOMAIN=@LOCALDOMAIN@
+# If the ENV variable is not set, determine its correct value
+if [ -z "${GLOBUS_HOSTNAME}" ] ; then
+
+  # Set the _fullname based upon Globus's hostname command
+  if [ -x "${libexecdir}/globus-libc-hostname" ]; then
+    _fullname="`${libexecdir}/globus-libc-hostname`"
+  fi
+
+  # if failed to set, use the system's hostname command
+  if [ -z "${_fullname}" ] ; then
+    _fullname=`${GLOBUS_SH_HOSTNAME-hostname}`
+  fi
+
+  _basename="`echo ${_fullname} | ${GLOBUS_SH_CUT-cut} -d. -f1`"
  
-if [ -x ${libexecdir}/globus-libc-hostname ]; then
-    FULLNAME="`${libexecdir}/globus-libc-hostname`"
-    # make sure command ran successfully
-    if [ ! $? = 0 ]
-    then
-       FULLNAME=`@GLOBUS_SH_HOSTNAME@`
-    fi
-else
-    FULLNAME=`@GLOBUS_SH_HOSTNAME@`
-fi
-    BASENAME=`@GLOBUS_SH_HOSTNAME@ | ${GLOBUS_SH_CUT-cut} -d. -f1`
- 
-if [ "X$FULLNAME" = "X$BASENAME" ] ; then
+  if [ "X$_fullname" = "X$_basename" ] ; then
     # Its not fully qualified
-    GLOBUS_HOSTNAME="${BASENAME}.${LOCALDOMAIN}"
-else
-    GLOBUS_HOSTNAME="$FULLNAME"
+    _fullname="${_basename}.${GLOBUS_LOCALDOMAIN}"
+  fi
+
+  GLOBUS_HOSTNAME="`echo ${_fullname} | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z'`"
 fi
 
-GLOBUS_HOSTNAME="`echo $GLOBUS_HOSTNAME | ${GLOBUS_SH_TR-tr} 'A-Z' 'a-z'`"
+GLOBUS_DOMAINNAME="`echo $GLOBUS_HOSTNAME | ${GLOBUS_SH_CUT-cut} -s -d '.' -f '2-'`"
 
-echo $GLOBUS_HOSTNAME
 export GLOBUS_HOSTNAME
+export GLOBUS_DOMAINNAME
+
+case "${PROGRAM_NAME}" in
+
+  globus-hostname)
+    echo $GLOBUS_HOSTNAME
+    ;;
+  globus-domainname)
+    echo $GLOBUS_DOMAINNAME
+    ;;
+
+esac
+
+
