This commit was manufactured by cvs2svn to create branch 'gridftp_enhancements_2_branch_2'.
Sprout from mds_2_2_branch 2002-05-13 21:02:11 UTC cvs2git 'This commit was manufactured by cvs2svn to create branch 'mds_2_2_branch'.'
Cherrypick from master 2002-05-17 15:30:47 UTC smartin '.':
    common/setup/dirt.sh
    common/setup/setup-globus-common-test
    common/source/dirt.sh
    common/source/programs/globus-sh-exec
    core/setup/dirt.sh
    core/setup/findshelltools.in
    core/setup/globus-sh-tools.sh.in
    core/source/aclocal/acdoxygen.m4
    core/source/dirt.sh
    gram/jobmanager/setup/program/dirt.sh
    gram/jobmanager/setup/program/setup-globus-gram-job-manager.pl
    gram/jobmanager/source/dirt.sh
    gram/jobmanager/source/globus-personal-gatekeeper
    gsi/gss_assist/source/dirt.sh
    gsi/gss_assist/source/pkgdata/pkg_data_src.gpt.in
    gsi/gssapi/source/dirt.sh
    gsi/gssapi/source/pkgdata/pkg_data_src.gpt.in
    gsi/ssl_utils/setup/dirt.sh
    gsi/ssl_utils/setup/pkgdata/pkg_data_src.gpt.in
    gsi/ssl_utils/source/dirt.sh
    gsi/ssl_utils/source/pkgdata/pkg_data_src.gpt.in
    io/source/configure.in
    io/source/dirt.sh
Delete:
    CVSROOT/checkoutlist
    CVSROOT/commit_prep.pl
    CVSROOT/commitinfo
    CVSROOT/config
    CVSROOT/cvswrappers
    CVSROOT/editinfo
    CVSROOT/log_accum.pl
    CVSROOT/modules
    CVSROOT/notify
    CVSROOT/rcsinfo
    CVSROOT/taginfo
    CVSROOT/verifymsg

diff --git a/common/setup/setup-globus-common-test b/common/setup/setup-globus-common-test
--- a/common/setup/setup-globus-common-test
+++ b/common/setup/setup-globus-common-test
@@ -11,12 +11,12 @@ fi
 
 . $GLOBUS_LOCATION/libexec/globus-sh-tools.sh
 
-if test "x$GLOBUS_PERL" = "x"; then
-    echo "ERROR Please specify GLOBUS_PERL" >&2
+if test "x$GLOBUS_SH_PERL" = "x"; then
+    echo "ERROR Please specify GLOBUS_SH_PERL" >&2
     exit 1
 fi
 
-PERL="$GLOBUS_PERL"
+PERL="$GLOBUS_SH_PERL"
 
 for i in $GLOBUS_LOCATION/test/globus_common*.pl \
          $GLOBUS_LOCATION/test/run-common-tests.pl; do
