fix argument parsing

diff --git a/gass/server_ez/source/globus-gass-server-shutdown.in b/gass/server_ez/source/globus-gass-server-shutdown.in
--- a/gass/server_ez/source/globus-gass-server-shutdown.in
+++ b/gass/server_ez/source/globus-gass-server-shutdown.in
@@ -1,12 +1,30 @@
 #! @SH@
 
+if test -z "${GLOBUS_LOCATION}"; then
+    echo ""
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory
+ before"
+    echo "running this script"
+    echo ""
+    exit 1
+fi
+
+
 . ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 globus_source ${libexecdir}/globus-sh-tools.sh
 
+PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
 
-progname=`echo "$0" | ${GLOBUS_SH_SED-sed} -e 's|.*/||'`
+PROGRAM_VERSION=`echo '$Revision$'| ${GLOBUS_SH_SED-sed} -e 's|\\$||g' -e 's|Revision: \(.*\)|\1|'`
 
-short_usage="$progname [-help] [-usage] [-version] <GASS-URL>"
+VERSION="@VERSION@"
+
+PACKAGE="@PACKAGE@"
+
+DIRT_TIMESTAMP="@DIRT_TIMESTAMP@"
+DIRT_BRANCH_ID="@DIRT_BRANCH_ID@"
+
+short_usage="$PROGRAM_NAME [-help] [-usage] [-version] <GASS-URL>"
 
 long_usage ()
 {
@@ -24,7 +42,7 @@ Syntax: ${short_usage}
 EOF
 }
 
-globus_source ${libexecdir}/globus-args-parser-header
+globus_source ${libexecdir}/globus-args-parser-header $@
 
 if [ "$#" -ne 1 ]; then
     globus_args_option_error "" "GASS URL must be provided"
