missing file

diff --git a/gass/server_ez/source/globus-gass-server-shutdown.in b/gass/server_ez/source/globus-gass-server-shutdown.in
--- a/gass/server_ez/source/globus-gass-server-shutdown.in
+++ b/gass/server_ez/source/globus-gass-server-shutdown.in
@@ -28,17 +28,11 @@ sysconfdir="@sysconfdir@"
 sharedstatedir="@sharedstatedir@"
 localstatedir="@localstatedir@"
 
-if [ -r ${libexecdir}/globus-script-initializer ]; then
-    . ${libexecdir}/globus-script-initializer 
-else
-    echo "Unable to locate globus-script-initializer" 1>&2
-fi
+PATH="${bindir}:${sbindir}:${libexecdir}:${PATH}"
 
-globus_source ${libexecdir}/globus-sh-tools.sh
+PROGRAM_NAME="${0##*/}"
 
-PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
-
-PROGRAM_VERSION=`echo '$Revision$'| ${GLOBUS_SH_SED-sed} -e 's|\\$||g' -e 's|Revision: \(.*\)|\1|'`
+PROGRAM_VERSION="@VERSION@"
 
 VERSION="@VERSION@"
 
@@ -51,7 +45,7 @@ short_usage="$PROGRAM_NAME [-help] [-usage] [-version] <GASS-URL>"
 
 long_usage ()
 {
-    ${GLOBUS_SH_CAT-cat} >&2 <<EOF
+    cat >&2 <<EOF
 
 Syntax: ${short_usage}
 
@@ -65,11 +59,82 @@ Syntax: ${short_usage}
 EOF
 }
 
-globus_source ${libexecdir}/globus-args-parser-header $@
+globus_args_short_usage()
+{
+    cat 1>&2 <<EOF
+
+Syntax : ${short_usage}
+
+Use -help to display full usage.
+
+EOF
+}
+
+globus_args_option_error()
+{
+    cat 1>&2 <<EOF
+
+ERROR: option $1 : $2
+EOF
+    globus_args_short_usage
+    exit 1
+}
+
+globus_args_unrecognized_option()
+{
+    globus_args_option_error $1 "unrecognized option"
+    exit 1
+}	
+
+while [ $# -gt 0 ]; do
+    arg="$1"
+    shift
+    case "${arg}" in
+        -help | -h | --help | -usage | --usage)
+            long_usage
+            exit 0
+            ;;
+        -version|--version)
+            if [ "X${PROGRAM_NAME}" != "X" -a \
+                  "X${PROGRAM_VERSION}" != "X" ]; then
+                echo "${PROGRAM_NAME}: ${PROGRAM_VERSION}"
+            elif [ "X${PACKAGE}" != "X" -a \
+                   "X${VERSION}" != "X" ]; then
+                echo "${PACKAGE}: ${VERSION}"
+            else
+                echo "No version information available."
+            fi
+            exit 0
+            ;;
+        -versions|--versions)
+            AT=@
+            if [ -n "${PACKAGE}" -a -n "${VERSION}" -a \
+                 -n "${DIRT_TIMESTAMP}" -a -n "${DIRT_BRANCH_ID}" -a \
+                 "X${DIRT_TIMESTAMP}" != "X${AT}DIRT_TIMESTAMP${AT}" -a \
+                 "X${DIRT_BRANCH_ID}" != "X${AT}DIRT_BRANCH_ID${AT}" ];
+            then
+                echo "${PACKAGE}: ${VERSION} (${DIRT_TIMESTAMP}-${DIRT_BRANCH_ID})"
+            else
+                echo "No DiRT information available."
+            fi
+            exit 0;
+            ;;
+        --)
+            break
+            ;;
+        *)
+            set -- "$arg" "$@"
+            break;
+            ;;
+    esac
+done
 
 if [ "$#" -ne 1 ]; then
     globus_args_option_error "" "GASS URL must be provided"
 fi
 
-${bindir}/globus-url-copy file:/etc/group "$1"/dev/globus_gass_client_shutdown > /dev/null 2>&1
-
+if ! command -v globus-url-copy > /dev/null; then
+    echo "Unable to find globus-url-copy"
+    exit 1
+fi
+globus-url-copy file:/etc/group "$1"/dev/globus_gass_client_shutdown > /dev/null 2>&1
