Update gss_assist to latest version of GPT.

diff --git a/gsi/gss_assist/source/bootstrap b/gsi/gss_assist/source/bootstrap
--- a/gsi/gss_assist/source/bootstrap
+++ b/gsi/gss_assist/source/bootstrap
@@ -1,5 +1,14 @@
 #! /bin/sh
 
+error()
+{
+    echo ""
+    echo "ERROR: bootstrap failed!"
+    echo ""
+    exit 1
+}
+
+
 # check for autotools
 
 for program in automake aclocal autoconf autoheader
@@ -18,23 +27,26 @@ if test "x$GLOBUS_INSTALL_PATH" = "x"; then
 fi
 
 echo "running aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal"
-aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal
+aclocal -I $GLOBUS_INSTALL_PATH/share/globus_aclocal || error
 
+if test -f acconfig.h ; then
 echo "running autoheader"
-autoheader
+    autoheader || error
+fi
 
-if test ! -L globus_automake_targets; then
+if test ! -h globus_automake_targets; then
     echo "installing extra automake files"
     ln -s $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_targets \
     globus_automake_targets
     ln -s $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_rules \
     globus_automake_rules
-	ln -s $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_top_rules \
+    ln -s $GLOBUS_INSTALL_PATH/share/globus_aclocal/automake_top_rules \
     globus_automake_top_rules
 fi
 
-echo "running automake -c -a --foreign"
-automake -c -a --foreign
+echo "running automake --copy -add-missing --foreign"
+automake --copy --add-missing --foreign || \
+  automake --copy --add-missing --foreign  || error
 
 echo "running autoconf"
-autoconf
+autoconf || error
