handle trusty os-release not having parsable codename

diff --git a/packaging/debian/globus-toolkit-repo/debian/globus-toolkit-repo.postinst b/packaging/debian/globus-toolkit-repo/debian/globus-toolkit-repo.postinst
--- a/packaging/debian/globus-toolkit-repo/debian/globus-toolkit-repo.postinst
+++ b/packaging/debian/globus-toolkit-repo/debian/globus-toolkit-repo.postinst
@@ -70,11 +70,27 @@ xj7TEZmv
 -----END PGP PUBLIC KEY BLOCK-----
 EOF
 
-if [ -f /etc/os-release ]; then
-    codename="$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)"
-elif [ -f /etc/lsb-release ]; then
+# Why is this so hard
+if [ -f /etc/lsb-release ]; then
     codename="$(awk -F= '/DISTRIB_CODENAME=/ {print $2}' /etc/lsb-release)"
+elif [ -f /etc/os-release ]; then
+    codename="$(awk -F"[)(]+" '/VERSION=/ {print $2}' /etc/os-release)"
 fi
+
+if [ -z "$codename" ] && command -v lsb_release > /dev/null; then
+    codename="$(lsb_release -cs)"
+fi
+
+if [ -z "$codename" ]; then
+    codename="$(python -c "import platform; print platform.linux_distribution()[2]")"
+fi
+
+if [ -z "$codename" ]; then
+    echo "Error determining OS codename" 1>&2
+    exit 1
+fi
+
+
 data="/usr/share/globus-toolkit-repo/sources.list.d"
 list_d="/etc/apt/sources.list.d"
 
