Packaging fixes

diff --git a/gsi/cert_utils/source/programs/grid-cert-info.in b/gsi/cert_utils/source/programs/grid-cert-info.in
--- a/gsi/cert_utils/source/programs/grid-cert-info.in
+++ b/gsi/cert_utils/source/programs/grid-cert-info.in
@@ -35,18 +35,11 @@ sysconfdir="@sysconfdir@"
 sharedstatedir="@sharedstatedir@"
 localstatedir="@localstatedir@"
 
-if [ -r ${libexecdir}/globus-script-initializer ]; then
-    . ${libexecdir}/globus-script-initializer
-else
-    echo "Unable to locate globus-script-initializer" 1>&2
-    exit 1
-fi
+PATH=${bindir}:${sbindir}:${PATH}
 
-globus_source ${libexecdir}/globus-sh-tools.sh
+PROGRAM_NAME=`echo $0 | sed 's|.*/||g'`
 
-PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
-
-PROGRAM_VERSION=`echo '$Revision$'| ${GLOBUS_SH_SED-sed} -e 's|\\$||g' -e 's|Revision: \(.*\)|\1|'`
+PROGRAM_VERSION="@VERSION@"
 
 VERSION="@VERSION@"
 
@@ -58,7 +51,7 @@ DIRT_BRANCH_ID="@DIRT_BRANCH_ID@"
 short_usage="$PROGRAM_NAME [-help] [-file certfile] [-all] [-subject] [...]"
 
 long_usage () {
-    ${GLOBUS_SH_CAT-cat} >&2 <<EOF
+    cat >&2 <<EOF
 
 ${short_usage}
 
@@ -128,22 +121,12 @@ certificate_format()
 }
 
 
-globus_source $libexecdir/globus-args-parser-header $@
-
-
-#SSL related needs
-if test -x ${bindir}/openssl; then
-    SSL_EXEC=${bindir}/openssl
-else
-    SSL_EXEC="openssl"
-fi
-
-if ! ${SSL_EXEC} version > /dev/null 2> /dev/null; then
-    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+if ! openssl version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in PATH" 1>&2
     exit 1
 fi
 
-# DEFault Generated Files
+# Default Generated Files
 cert_format=x509
 openssl_options=""
 toprint=""
@@ -152,9 +135,64 @@ toprint=""
 #
 certfile=`find_default_credential`
 
+globus_args_short_usage()
+{
+    cat 1>&2 <<EOF
+
+Syntax : ${short_usage}
+
+Use -help to display full usage.
+
+EOF
+}
+
+globus_args_option_error()
+{
+    cat 1>&2 <<EOF
+
+ERROR: option $1 : $2
+EOF
+    globus_args_short_usage
+    exit 1
+}
+
+globus_args_unrecognized_option()
+{
+    globus_args_option_error $1 "unrecognized option"
+    exit 1
+}	
 while [ "X$1" != "X" ]; do
     case $1 in
-    -file| -f)
+    -help | -h | --help | -usage | --usage)
+        long_usage
+        exit 0
+        ;;
+    -version|--version)
+        if [ "X${PROGRAM_NAME}" != "X" -a \
+              "X${PROGRAM_VERSION}" != "X" ]; then
+            echo "${PROGRAM_NAME}: ${PROGRAM_VERSION}"
+        elif [ "X${PACKAGE}" != "X" -a \
+               "X${VERSION}" != "X" ]; then
+            echo "${PACKAGE}: ${VERSION}"
+        else
+            echo "No version information available."
+        fi
+        exit 0
+        ;;
+    -versions|--versions)
+        __AT=@
+        if [ -n "${PACKAGE}" -a -n "${VERSION}" -a \
+             -n "${DIRT_TIMESTAMP}" -a -n "${DIRT_BRANCH_ID}" -a \
+             "X${DIRT_TIMESTAMP}" != "X${__AT}DIRT_TIMESTAMP${__AT}" -a \
+             "X${DIRT_BRANCH_ID}" != "X${__AT}DIRT_BRANCH_ID${__AT}" ];
+        then
+            echo "${PACKAGE}: ${VERSION} (${DIRT_TIMESTAMP}-${DIRT_BRANCH_ID})"
+        else
+            echo "No DiRT information available."
+        fi
+        exit 0;
+        ;;
+    -file| -f | --file)
         if [ -n "$2" -a -f "$2" -a -r "$2" ]; then
             certfile=$2
         else
@@ -166,25 +204,25 @@ while [ "X$1" != "X" ]; do
         fi
         shift
         ;;
-    -all)
+    -all | -all)
 	toprint="$toprint -text"
 	;;
-    -subject|-s)
+    -subject|-s | --subject)
 	toprint="$toprint SUBJECT"
 	;;
-    -issuerhash|-ih)
+    -issuerhash|-ih | --issuerhash)
 	toprint="$toprint -issuer_hash"
 	;;
-    -issuer|-i)
+    -issuer|-i | --issuer)
 	toprint="$toprint -issuer"
 	;;
-    -startdate|-sd)
+    -startdate|-sd|--startdate)
 	toprint="$toprint -startdate"
 	;;
-    -enddate|-ed)
+    -enddate|-ed|--enddate)
 	toprint="$toprint -enddate"
 	;;
-    -rfc2253)
+    -rfc2253|--rfc2253)
         openssl_options='-nameopt rfc2253'
         ;;
     *)
@@ -211,10 +249,10 @@ fi
  
 if [ "$cert_format" = pkcs12 ]; then
     echo "Credentials are in pkcs12 format, OpenSSL will prompt for p12 password"
-    cert_data="`${SSL_EXEC} pkcs12 -nokeys -clcerts -nomacver -in ${certfile}`"
-    command_stub="${SSL_EXEC} x509 -noout $openssl_options"
+    cert_data="`openssl pkcs12 -nokeys -clcerts -nomacver -in ${certfile}`"
+    command_stub="openssl x509 -noout $openssl_options"
 else
-    command_stub="${SSL_EXEC} x509 -noout -in ${certfile} $openssl_options"
+    command_stub="openssl x509 -noout -in ${certfile} $openssl_options"
 fi
 
 
@@ -229,17 +267,17 @@ if test $? -ne 0 ; then
     exit 1
 fi
 
-subject=`echo ${subject} | ${GLOBUS_SH_SED-sed} 's%^subject=\ *%%'`
+subject=`echo ${subject} | sed 's%^subject=\ *%%'`
 
 eval set -- "$toprint"
 for i in "$@"; do
     case "$i" in
     -*)
-	echo "$cert_data" | eval "{ ${command_stub} $i || exit $?; } | ${GLOBUS_SH_SED-sed} 's/^[a-zA-Z]*=[ ]*//'"
+	echo "$cert_data" | eval "{ ${command_stub} $i || exit $?; } | sed 's/^[a-zA-Z]*=[ ]*//'"
 	;;
     SUBJECT)
 	# Do not show the proxy levels
-	echo "${subject}" | ${GLOBUS_SH_SED-sed} -e 's%/CN=proxy%%g' -e 's%/CN=limited proxy%%g'
+	echo "${subject}" | sed -e 's%/CN=proxy%%g' -e 's%/CN=limited proxy%%g'
 	;;
     esac
 done
diff --git a/gsi/cert_utils/source/programs/grid-cert-request.in b/gsi/cert_utils/source/programs/grid-cert-request.in
--- a/gsi/cert_utils/source/programs/grid-cert-request.in
+++ b/gsi/cert_utils/source/programs/grid-cert-request.in
@@ -22,13 +22,13 @@ printDirections ()
   printThis=0
   if [ -f $DIRECTIONS_FILE ] ; then
     while read line || test ! -z "${line}" ; do
-      if test -n "`echo $line | ${GLOBUS_SH_GREP-grep} \"END $1 TEXT\"`" ; then
+      if test -n "`echo $line | grep \"END $1 TEXT\"`" ; then
         break
       fi
       if [ "$printThis" = "1" ]; then
         echo "`eval echo \"$line\"`"
       fi
-      if test -n "`echo $line | ${GLOBUS_SH_GREP-grep} \"BEGIN $1 TEXT\"`" ; then
+      if test -n "`echo $line | grep \"BEGIN $1 TEXT\"`" ; then
         printThis=1
       fi
     done < $DIRECTIONS_FILE
@@ -50,14 +50,7 @@ sysconfdir="@sysconfdir@"
 sharedstatedir="@sharedstatedir@"
 localstatedir="@localstatedir@"
 
-if [ -r ${libexecdir}/globus-script-initializer ]; then
-    . ${libexecdir}/globus-script-initializer
-else
-    echo "Unable to locate globus-script-initializer" 1>&2
-    exit 1
-fi
-
-globus_source ${libexecdir}/globus-sh-tools.sh
+PATH=${bindir}:${sbindir}:${PATH}
 
 if [ ! -z "${GRID_SECURITY_DIR}" ] ; then
     if [ -r "${GRID_SECURITY_DIR}/globus-user-ssl.conf" ] && 
@@ -110,9 +103,9 @@ fi
 # globus gatekeeper daemon, use the -nopw option, so the
 # key is not protected by pass phrase. 
 #
-PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
+PROGRAM_NAME=`echo $0 | sed 's|.*/||g'`
 
-PROGRAM_VERSION=`echo '$Revision$'| ${GLOBUS_SH_SED-sed} -e 's|\\$||g' -e 's|Revision: \(.*\)|\1|'`
+PROGRAM_VERSION="@VERSION@"
 
 VERSION="@VERSION@"
 
@@ -131,7 +124,7 @@ short_usage="$PROGRAM_NAME [-help] [ options ...]"
 
 long_usage ()
 {
-    ${GLOBUS_SH_CAT-cat} >&2 <<EOF
+    cat >&2 <<EOF
 
 ${short_usage}
 
@@ -180,8 +173,6 @@ ${short_usage}
 EOF
 }
 
-globus_source ${libexecdir}/globus-args-parser-header $@
-
 ###########################################################
 # set_non_default_ca
 #   Change the CA used for generating the certificate
@@ -209,9 +200,9 @@ set_non_default_ca()
         for cert in ${trusted_certs_dir}/*.0; do
             if test -r "${cert}" ; then
                 eval "CA${index}=${cert}"
-                TEMP_SUBJECT=`${SSL_EXEC} x509 -in ${cert} -noout -subject`
-                eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
-                eval "CA_HASH${index}=`${SSL_EXEC} x509 -in ${cert} -noout -hash`"
+                TEMP_SUBJECT=`openssl x509 -in ${cert} -noout -subject`
+                eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | sed -e \"s|subject= ||\"`\""
+                eval "CA_HASH${index}=`openssl x509 -in ${cert} -noout -hash`"
                 eval "echo \"$index)  \${CA_HASH${index}} - \${CA_SUBJECT${index}}\""
                 index=`expr $index + 1`
             fi
@@ -238,8 +229,8 @@ set_non_default_ca()
             echo 
             exit 1
         fi
-        TEMP_SUBJECT=`${SSL_EXEC} x509 -in ${trusted_certs_dir}/${CA_HASH}.0 -noout -subject`
-        eval "CA_SUBJECT=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
+        TEMP_SUBJECT=`openssl x509 -in ${trusted_certs_dir}/${CA_HASH}.0 -noout -subject`
+        eval "CA_SUBJECT=\"`echo ${TEMP_SUBJECT} | sed -e \"s|subject= ||\"`\""
     fi
 
     echo
@@ -261,7 +252,7 @@ set_non_default_ca()
 
 abort_cleanup () 
 {
-    ${GLOBUS_SH_RM-rm} -f ${CERT_FILE} ${KEY_FILE} \
+    rm -f ${CERT_FILE} ${KEY_FILE} \
                           ${REQUEST_FILE} ${RAND_TEMP} \
                           ${REQ_HEAD} ${REQ_INPUT} ${REQ_OUTPUT} ${REQ_CONF}
 }
@@ -290,6 +281,32 @@ absolute_path ()
 # read_command_line
 #   Command line parsing
 ###########################################################
+globus_args_short_usage()
+{
+    cat 1>&2 <<EOF
+
+Syntax : ${short_usage}
+
+Use -help to display full usage.
+
+EOF
+}
+
+globus_args_option_error()
+{
+    cat 1>&2 <<EOF
+
+ERROR: option $1 : $2
+EOF
+    globus_args_short_usage
+    exit 1
+}
+
+globus_args_unrecognized_option()
+{
+    globus_args_option_error $1 "unrecognized option"
+    exit 1
+}	
 
 read_command_line () 
 {
@@ -297,18 +314,43 @@ read_command_line ()
 
     while [ "X$1" !=  "X" ]
     do
-        case $1 in
-            -\?|-h|-help|-usage)
+        case "$1" in
+            -help | -h | --help | -usage | --usage)
                 long_usage
                 exit 0
                 ;;
-            -cn | -commonname)
+            -version|--version)
+                if [ "X${PROGRAM_NAME}" != "X" -a \
+                      "X${PROGRAM_VERSION}" != "X" ]; then
+                    echo "${PROGRAM_NAME}: ${PROGRAM_VERSION}"
+                elif [ "X${PACKAGE}" != "X" -a \
+                       "X${VERSION}" != "X" ]; then
+                    echo "${PACKAGE}: ${VERSION}"
+                else
+                    echo "No version information available."
+                fi
+                exit 0
+                ;;
+            -versions|--versions)
+                __AT=@
+                if [ -n "${PACKAGE}" -a -n "${VERSION}" -a \
+                     -n "${DIRT_TIMESTAMP}" -a -n "${DIRT_BRANCH_ID}" -a \
+                     "X${DIRT_TIMESTAMP}" != "X${__AT}DIRT_TIMESTAMP${__AT}" -a \
+                     "X${DIRT_BRANCH_ID}" != "X${__AT}DIRT_BRANCH_ID${__AT}" ];
+                then
+                    echo "${PACKAGE}: ${VERSION} (${DIRT_TIMESTAMP}-${DIRT_BRANCH_ID})"
+                else
+                    echo "No DiRT information available."
+                fi
+                exit 0;
+                ;;
+            -cn | -commonname | --commonname)
                 COMMON_NAME="$2"
                 shift ; shift
                 ;;
-            -host)
+            -host | --host)
                 SERVICE_HOST="$2"
-                SERVICE_HOST=`echo ${SERVICE_HOST}|${GLOBUS_SH_TR-tr} 'A-Z' 'a-z'`
+                SERVICE_HOST=`echo ${SERVICE_HOST}|tr 'A-Z' 'a-z'`
                 if echo ${SERVICE_HOST}|grep "localhost" >/dev/null || \
                    echo ${SERVICE_HOST}|grep "localdomain" >/dev/null; then
                     globus_args_option_error "$1" "$2 may not contain localhost or localdomain"
@@ -316,47 +358,47 @@ read_command_line ()
                 NO_DES="-nodes"
                 shift ; shift
                 ;;
-            -dns)
+            -dns | --dns)
                 DNS_NAME_EXTENSIONS="$2"
                 shift; shift;
                 ;;
-            -ip)
+            -ip | --ip)
                 IP_ADDRESS_EXTENSIONS="$2"
                 shift; shift;
                 ;;
-            -service)
+            -service | --service)
                 SERVICE="$2"
-                SERVICE=`echo ${SERVICE}|${GLOBUS_SH_TR-tr} 'A-Z' 'a-z'`
+                SERVICE=`echo ${SERVICE}|tr 'A-Z' 'a-z'`
                 shift ; shift
                 ;;
-            -dir)
+            -dir | --dir)
                 TARGET_DIR="$2"
                 TARGET_DIR="`absolute_path ${TARGET_DIR}`"
                 shift ; shift
                 ;;
-            -prefix)
+            -prefix | --prefix)
                 PREFIX="$2"
                 shift ; shift
                 ;;
-            -nopw|-nodes|-nopassphrase)
+            -nopw|-nodes|-nopassphrase | --nopw | --nodes | --nopassphrase)
                 NO_DES="-nodes"
                 shift
                 ;;
-            -verbose)
+            -verbose | --verbose)
                 VERBOSE="yes"
                 shift
                 ;;
-            -int|-interactive)
+            -int|-interactive | --int | --interactive)
                 INTERACTIVE="TRUE"
                 shift
                 ;;
-            -force)
+            -force | --force)
                 FORCE="TRUE"
                 shift
                 ;;
-            -ca)
+            -ca | --ca)
                 if [ ! -z "$2" ] && \
-                   [ -z "`echo $2 | ${GLOBUS_SH_SED-sed} -e \"s|[^-]*||g\"`" ]
+                   [ -z "`echo $2 | sed -e \"s|[^-]*||g\"`" ]
                 then
                     nondefaultca=$2
                     shift
@@ -427,7 +469,7 @@ create_input_file ()
     # Parse the ssleay configuration file, to determine the
     # correct default parameters
 
-    ${GLOBUS_SH_AWK-awk}  < $_config_file '
+    awk  < $_config_file '
  
   /^\[ req_distinguished_name \]/ {
      start_parsing=1;
@@ -481,7 +523,7 @@ create_conf_file ()
     while read line; do
         echo "$line"
 
-        if echo "$line" | ${GLOBUS_SH_GREP-grep} '\[ v3_req \]' > /dev/null 2>&1 ; then
+        if echo "$line" | grep '\[ v3_req \]' > /dev/null 2>&1 ; then
             create_subjectAltName
         fi
     done < $_config_file
@@ -494,7 +536,7 @@ create_conf_file ()
 create_request_header () 
 {
   if printDirections "REQUEST HEADER" ; then
-    ${GLOBUS_SH_CAT-cat} <<EOF
+    cat <<EOF
 This is a Certificate Request file:
 
 It should be mailed to ${GSI_CA_EMAIL_ADDR}
@@ -537,31 +579,31 @@ check4certs ()
     _exists="FALSE"
 
     if [ -r ${REQUEST_FILE} ] ; then
-        ${GLOBUS_SH_PRINTF-printf} "\n    ${REQUEST_FILE} already exists" 1>&2
-        ${GLOBUS_SH_CHMOD-chmod} u+w ${REQUEST_FILE}
+        printf "\n    ${REQUEST_FILE} already exists" 1>&2
+        chmod u+w ${REQUEST_FILE}
         _exists=TRUE
     fi
     
     if [ -r ${CERT_FILE} ] ; then
-        ${GLOBUS_SH_PRINTF-printf} "\n    ${CERT_FILE} already exists" 1>&2
-        ${GLOBUS_SH_CHMOD-chmod} u+w ${CERT_FILE}
+        printf "\n    ${CERT_FILE} already exists" 1>&2
+        chmod u+w ${CERT_FILE}
         _exists=TRUE
     fi
     
     if [ -r ${KEY_FILE} ] ; then
-        ${GLOBUS_SH_PRINTF-printf} "\n    ${KEY_FILE} already exists" 1>&2
-        ${GLOBUS_SH_CHMOD-chmod} u+w ${KEY_FILE}
+        printf "\n    ${KEY_FILE} already exists" 1>&2
+        chmod u+w ${KEY_FILE}
         _exists=TRUE
     fi
 
   
     if [ "X$_exists" = "XTRUE" ] ; then
         if [ "X$FORCE" = "XTRUE" ] ; then
-            ${GLOBUS_SH_RM-rm} -f ${CERT_FILE} ${KEY_FILE} ${REQUEST_FILE}
+            rm -f ${CERT_FILE} ${KEY_FILE} ${REQUEST_FILE}
             echo
             echo
         else 
-            ${GLOBUS_SH_PRINTF-printf} "\n\nIf you wish to overwrite, run the script again with -force.\n" 1>&2
+            printf "\n\nIf you wish to overwrite, run the script again with -force.\n" 1>&2
             exit 1
         fi
     fi
@@ -577,15 +619,15 @@ check4certs ()
 setup_target_dir () 
 {
     if test ! -d ${TARGET_DIR} ; then
-        ${GLOBUS_SH_MKDIR-mkdir} ${TARGET_DIR}
+        mkdir ${TARGET_DIR}
         if [ $? -ne 0 ] ; then
-            ${GLOBUS_SH_PRINTF-printf} "\n\nUnable to create ${TARGET_DIR}. Please make sure that you have the right to create this directory before running this script.\n" 1>&2
+            printf "\n\nUnable to create ${TARGET_DIR}. Please make sure that you have the right to create this directory before running this script.\n" 1>&2
             exit $?
         fi 
     fi
 
     if test ! -w ${TARGET_DIR} ; then
-        ${GLOBUS_SH_PRINTF-printf} "\n\nUnable to access ${TARGET_DIR}. Please make sure that you have the right to create files in this directory before running this script.\n" 1>&2
+        printf "\n\nUnable to access ${TARGET_DIR}. Please make sure that you have the right to create files in this directory before running this script.\n" 1>&2
         exit 1
     fi
 }
@@ -604,17 +646,17 @@ get_user_CN ()
     # 3. Prompt the user
 
     if [ -z "${_common_name}" ] ; then 
-        ${GLOBUS_SH_FINGER-finger} -lm ${USERID}  >/dev/null 2>&1
+        finger -lm ${USERID}  >/dev/null 2>&1
         if [ $? -eq 0 ] ; then 
-            _common_name="`${GLOBUS_SH_FINGER-finger} -lm ${USERID}      |\
-                           ${GLOBUS_SH_GREP-grep} ${USERID}              |\
-                           ${GLOBUS_SH_AWK-awk} -F: '{ print $3; exit }' |\
-                           ${GLOBUS_SH_CUT-cut} -c2- `"
+            _common_name="`finger -lm ${USERID}      |\
+                           grep ${USERID}              |\
+                           awk -F: '{ print $3; exit }' |\
+                           cut -c2- `"
         fi
     fi
 
    if [ -z "${_common_name}" ] || [ "${_common_name}" = "(null)" ];  then
-      ${GLOBUS_SH_PRINTF-printf} "Enter your name, e.g., John Smith: " 1>&2
+      printf "Enter your name, e.g., John Smith: " 1>&2
       read _common_name
    fi
 
@@ -637,11 +679,11 @@ get_host_CN ()
 
    if [ -z "${_common_name}" ] ; then 
         # Check SERVICE_HOST and make sure it looks like a FQDN
-        ${GLOBUS_SH_ECHO-echo} ${SERVICE_HOST} | \
-            ${GLOBUS_SH_GREP-grep} "\." >/dev/null 2>&1
+        echo ${SERVICE_HOST} | \
+            grep "\." >/dev/null 2>&1
         if [ $? -eq 1 ] ; then
-            ${GLOBUS_SH_ECHO-echo} "The hostname ${SERVICE_HOST} does not appear to be fully qualified." 1>&2
-            ${GLOBUS_SH_PRINTF-printf} "Do you wish to continue? [n] " 1>&2
+            echo "The hostname ${SERVICE_HOST} does not appear to be fully qualified." 1>&2
+            printf "Do you wish to continue? [n] " 1>&2
             read _response
 
             case X${_response} in
@@ -649,7 +691,7 @@ get_host_CN ()
                     ;;
 
                 *)
-                    ${GLOBUS_SH_ECHO-echo} "Aborting" 1>&2
+                    echo "Aborting" 1>&2
                     return 1
                     ;;
             esac
@@ -684,13 +726,13 @@ create_certs () {
     #------------------------
     # Create the Certificate File
     umask 022
-    ${GLOBUS_SH_TOUCH-touch} ${CERT_FILE}
+    touch ${CERT_FILE}
 
 
     #------------------------
     # Create some semi random data for key generation 
     umask 066
-    ${GLOBUS_SH_TOUCH-touch} ${RAND_TEMP}
+    touch ${RAND_TEMP}
     if [ -r /dev/urandom ] ; then
         head -1000 /dev/urandom >> ${RAND_TEMP} 2>&1
     fi
@@ -714,35 +756,35 @@ create_certs () {
     fi
 
     if test ! -z "${INTERACTIVE}" ; then
-        ${SSL_EXEC} req -new -keyout ${KEY_FILE} -out ${REQ_OUTPUT} \
+        openssl req -new -keyout ${KEY_FILE} -out ${REQ_OUTPUT} \
             -rand ${RAND_TEMP}:/var/adm/wtmp:/var/log/messages \
             -config ${used_config} ${NO_DES}
         RET=$?
-        ${GLOBUS_SH_RM-rm} -f ${RAND_TEMP}
+        rm -f ${RAND_TEMP}
     else
         create_input_file "${COMMON_NAME}" "${used_config}" > ${REQ_INPUT}
 
-        ${SSL_EXEC} req -new -keyout ${KEY_FILE} \
+        openssl req -new -keyout ${KEY_FILE} \
               -rand ${RAND_TEMP}:/var/adm/wtmp:/var/log/messages \
               -out ${REQ_OUTPUT} -config ${used_config} \
               ${NO_DES} < ${REQ_INPUT} 
         RET=$?
 
-        ${GLOBUS_SH_RM-rm} -f ${RAND_TEMP}
-        ${GLOBUS_SH_RM-rm} -f ${REQ_INPUT}
+        rm -f ${RAND_TEMP}
+        rm -f ${REQ_INPUT}
 
         # You can't separate the SSL output, it all goes to stderr
         # including the prompts.
         # Don't remove ssleay output on error as it may be useful
         
         if test ${RET} -eq 0 -a -z "${VERBOSE}" ; then
-            ${GLOBUS_SH_CLEAR-clear}
+            clear
         fi
     fi
 
     if [ ${RET} -ne 0 ] ; then
         echo "Error number ${RET} was returned by " 1>&2
-        echo "   ${SSL_EXEC}"                    1>&2
+        echo "   openssl"                    1>&2
         exit ${RET}
     fi
 
@@ -752,18 +794,18 @@ create_certs () {
     # Insert instructions into the request file
 
 
-    SUBJECT="`${SSL_EXEC} req -text -noout < ${REQ_OUTPUT} 2>&1 |\
-              ${GLOBUS_SH_GREP-grep} 'Subject:' | ${GLOBUS_SH_AWK-awk} -F: '{print $2}' |\
-              ${GLOBUS_SH_CUT-cut} -c2- `"
+    SUBJECT="`openssl req -text -noout < ${REQ_OUTPUT} 2>&1 |\
+              grep 'Subject:' | awk -F: '{print $2}' |\
+              cut -c2- `"
 
     #Convert the subject to the correct form.
-    SUBJECT=`echo "/"${SUBJECT} | ${GLOBUS_SH_SED-sed} -e 's|, |/|g'`
+    SUBJECT=`echo "/"${SUBJECT} | sed -e 's|, |/|g'`
 
     create_request_header >${REQ_HEAD}
 
     # Finalize the Request file.
-    ${GLOBUS_SH_CAT-cat} ${REQ_HEAD} ${REQ_OUTPUT} >${REQUEST_FILE}
-    ${GLOBUS_SH_RM-rm} -f ${REQ_HEAD} ${REQ_OUTPUT} ${REQ_CONF}
+    cat ${REQ_HEAD} ${REQ_OUTPUT} >${REQUEST_FILE}
+    rm -f ${REQ_HEAD} ${REQ_OUTPUT} ${REQ_CONF}
 }
 
 ###########################################################
@@ -832,15 +874,8 @@ emit_directions () {
 ###########################################################
 
 
-#SSL related variables
-if test -x ${bindir}/openssl; then
-    SSL_EXEC=${bindir}/openssl
-else
-    SSL_EXEC="openssl"
-fi
-
-if ! ${SSL_EXEC} version > /dev/null 2> /dev/null; then
-    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+if ! openssl version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in PATH" 1>&2
     exit 1
 fi
 
@@ -852,8 +887,17 @@ security_conf="${secconfdir}/grid-security.conf"
 
 # Info sent with the certificate
 SUBJECT=
-USERID="`${GLOBUS_SH_WHOAMI-whoami}`"
-HOST="`${bindir}/globus-hostname`"
+USERID="`whoami`"
+if command -v globus-hostname > /dev/null; then
+    HOST="`globus-hostname`"
+elif command -v hostname > /dev/null; then
+    HOST=`hostname`
+elif command -v uname > /dev/null; then
+    HOST=`uname -n`
+else
+    HOST=""
+fi
+
 SERVICE=
 SERVICE_HOST=
 INTERACTIVE=
@@ -863,7 +907,7 @@ CERT_FILE=
 KEY_FILE=
 REQUEST_FILE=
 
-CERTREQ="${bindir}/grid-cert-request"
+CERTREQ="grid-cert-request"
 
 # Parse the command line
 
@@ -929,7 +973,7 @@ create_certs
 
 RET=$?
 
-COMMON_NAME="`echo ${SUBJECT} | ${GLOBUS_SH_SED-sed} -e 's|^.*/CN=||'`"
+COMMON_NAME="`echo ${SUBJECT} | sed -e 's|^.*/CN=||'`"
 
 # print directions to screen
 emit_directions ${SERVICE}
