added grid-cert-renew.in changes committed to 2.2 branch

diff --git a/gsi/cert_utils/source/programs/grid-cert-renew.in b/gsi/cert_utils/source/programs/grid-cert-renew.in
--- a/gsi/cert_utils/source/programs/grid-cert-renew.in
+++ b/gsi/cert_utils/source/programs/grid-cert-renew.in
@@ -43,12 +43,13 @@ ${short_usage}
     Optional arguments:
       -help, -usage        : displays this message
       -debug               : extra output (if problem occurs)
-      -nopassphrase        : signals that this is a host certificate
+      -nopassphrase        : do not encrypt the new private key file 
       -sslexec    <path>   : location of SSL executable (${ssl_exec_name})
       -oldcert    <path>   : location of old certificate
       -oldkey     <path>   : location of old (private) key
       -newkey     <path>   : location of new (private) key
       -newcertreq <path>   : location of certificate renewal request
+      -version             : prints the version 
     Required Argument:
       <challenge>          : challenge text, as per email instructions.
 
@@ -92,7 +93,40 @@ bailout ()
 }
 trap bailout 1 2 3 6 15
 
+check_for_globus_ns() {
+    echo "$1" | ${GLOBUS_SH_AWK-awk} '
+BEGIN     { FS = ","; lastorg=0; lastou=0; hasgrid=0; }
 
+{
+    split($0, b, "/");
+    i=2;
+    while(b[i] != "")
+    {
+        split(b[i],c,"=");
+        if(tolower(c[1]) ~ /o/)
+        {
+            org[++lastorg]=c[2];
+        }
+        i++;
+    }
+}
+
+END {
+    for(i = lastorg; i > 0; i--)
+    {
+        if(tolower(org[i]) == "globus")
+        {
+            hasgrid=i;
+        }
+
+        if(tolower(org[i]) == "grid" && hasgrid == (i + 1))
+        {
+            print "YES";
+        }
+   }
+}
+'
+}
 
 #########################################################################
 # start
@@ -109,11 +143,6 @@ challenge=
 globusdir=${GLOBUS_LOCATION}
 debug=no
 sslexec_rsa_opts=-des3
-
-if [ $# -eq 0 ]; then
-    globus_args_short_usage
-    exit 0
-fi
 
 while [ -n "$1" ]; do
     case "$1" in
@@ -195,6 +224,20 @@ if [ ! -x ${sslexec} ]; then
     exit 1
 fi
 
+if [ ! -x ${bindir}/grid-cert-info ]; then
+    echo "Error: Couldn't execute: '${bindir}/grid-cert-info'" 1>&2
+    exit 1
+fi
+
+BASE_DN=`${bindir}/grid-cert-info -subject | sed -e "s|^\(\/[Oo]=[Gg][Rr][Ii][Dd]\/[Oo]=[Gg][Ll][Oo][Bb][Uu][Ss]\)\/.*|\1|"`
+
+IS_GLOBUS_NS=`check_for_globus_ns $BASE_DN`
+if [ "$IS_GLOBUS_NS" != "YES" ]; then
+    echo "Error: grid-cert-renew can only be used for certificates"
+    echo "       generated by the Globus CA.  (/O=Grid/O=Globus)"
+    exit 1;
+fi
+
 ${sslexec} version 1>/dev/null 2>/dev/null
 xxx=$?
 if [ ${xxx} -ne 0 ]; then
@@ -258,16 +301,14 @@ if [ ${debug} = yes ] ; then
 fi
 ${proxy_init} ${proxy_opts}
 xxx=$?
-while [ ${xxx} -gt 2 ] ; do
+if [ ${xxx} -ne 0 ] ; then
     if [ ${debug} = yes ] ; then
 	echo "DEBUG: got return value ${xxx}"
     fi
-    echo "" 
-    echo "    Try again..."
-    echo ""
-    ${proxy_init} ${proxy_opts}
-    xxx=$?
-done
+    echo "ERROR: Running grid-proxy-init"
+    echo "Use -debug for further information."
+    exit 1
+fi
 
 # 2. extract the private key, encrypt it in new passphrase
 #    and save it as new user key
@@ -280,8 +321,7 @@ ${GLOBUS_SH_RM-rm} -f ${newkey} ${newcertreq}
 ${GLOBUS_SH_CAT-cat} <<EOF
 
     2. Creating a new private key which will replace your old key that is
-       about to expire. The new key will be protected by a different
-       passphrase than your old. When prompted (twice), enter a passphrase
+       about to expire.  When prompted (twice) enter a passphrase 
        for the new key.
 
 EOF
