Replace @GLOBUS_SCRIPT_INITIALIZER@

diff --git a/gsi/cert_utils/source/programs/grid-cert-request.in b/gsi/cert_utils/source/programs/grid-cert-request.in
--- a/gsi/cert_utils/source/programs/grid-cert-request.in
+++ b/gsi/cert_utils/source/programs/grid-cert-request.in
@@ -37,11 +37,25 @@ printDirections ()
   return $printThis
 }
 
+prefix="${GLOBUS_LOCATION-@prefix@}"
+exec_prefix="@exec_prefix@"
+sbindir="@sbindir@"
+bindir="@bindir@"
+libdir="@libdir@"
+includedir="@includedir@"
+datarootdir="@datarootdir@"
+datadir="@datadir@"
+libexecdir="@libexecdir@"
+sysconfdir="@sysconfdir@"
+sharedstatedir="@sharedstatedir@"
+localstatedir="@localstatedir@"
 
-
-@GLOBUS_SCRIPT_INITIALIZER@
-
-. ${libexecdir}/globus-script-initializer
+if [ -r ${libexecdir}/globus-script-initializer ]; then
+    . ${libexecdir}/globus-script-initializer
+else
+    echo "Unable to locate globus-script-initializer" 1>&2
+    exit 1
+fi
 
 globus_source ${libexecdir}/globus-sh-tools.sh
 
diff --git a/gsi/gss_assist/source/programs/grid-mapfile-delete-entry.in b/gsi/gss_assist/source/programs/grid-mapfile-delete-entry.in
--- a/gsi/gss_assist/source/programs/grid-mapfile-delete-entry.in
+++ b/gsi/gss_assist/source/programs/grid-mapfile-delete-entry.in
@@ -21,9 +21,24 @@
 # grid-mapfile-delete-entry
 #
 
-@GLOBUS_SCRIPT_INITIALIZER@
+prefix="${GLOBUS_LOCATION-@prefix@}"
+exec_prefix="@exec_prefix@"
+sbindir="@sbindir@"
+bindir="@bindir@"
+includedir="@includedir@"
+datarootdir="@datarootdir@"
+datadir="@datadir@"
+libexecdir="@libexecdir@"
+sysconfdir="@sysconfdir@"
+sharedstatedir="@sharedstatedir@"
+localstatedir="@localstatedir@"
 
-. ${libexecdir}/globus-script-initializer
+if [ -r ${libexecdir}/globus-script-initializer ]; then
+    . ${libexecdir}/globus-script-initializer
+else
+    echo "Unable to locate globus-script-initializer" 1>&2
+    exit 1
+fi
 
 globus_source ${libexecdir}/globus-sh-tools.sh
 
