Merge fix to bug #6471 from 4.2 branch

diff --git a/gsi/cert_utils/source/programs/grid-cert-info.in b/gsi/cert_utils/source/programs/grid-cert-info.in
--- a/gsi/cert_utils/source/programs/grid-cert-info.in
+++ b/gsi/cert_utils/source/programs/grid-cert-info.in
@@ -22,16 +22,16 @@
 # Easily extract information from a user's cert.
 #
 
-if test -z "${GLOBUS_LOCATION}"; then
-    echo ""
-    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
-    echo "running this script"
-    echo ""
+if test -f ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer
+elif test -f ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer
+else
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before" 1>&2
+    echo "running this script" 1>&2
     exit 1
 fi
-
-. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
-globus_source ${GLOBUS_LOCATION}/libexec/globus-sh-tools.sh
+globus_source ${libexecdir}/globus-sh-tools.sh
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
 
@@ -98,9 +98,16 @@ globus_source $libexecdir/globus-args-parser-header $@
 
 
 #SSL related needs
-PATH=${GLOBUS_LOCATION}/bin:${PATH}
-SSL_EXEC="${GLOBUS_LOCATION}/bin/openssl"
-	
+if test -n "${GLOBUS_LOCATION}" -a -x ${bindir}/openssl; then
+    SSL_EXEC=${bindir}/openssl
+else
+    SSL_EXEC="openssl"
+fi
+
+if ! ${SSL_EXEC} version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+    exit 1
+fi
 
 # DEFault Generated Files
 cert_format=x509
diff --git a/gsi/cert_utils/source/programs/grid-cert-request.in b/gsi/cert_utils/source/programs/grid-cert-request.in
--- a/gsi/cert_utils/source/programs/grid-cert-request.in
+++ b/gsi/cert_utils/source/programs/grid-cert-request.in
@@ -39,16 +39,16 @@ printDirections ()
 
 
 
-if test -z "${GLOBUS_LOCATION}"; then
-    echo ""
-    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
-    echo "running this script"
-    echo ""
+if test -f ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer
+elif test -f ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer
+else
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before" 1>&2
+    echo "running this script" 1>&2
     exit 1
 fi
-
-. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
-globus_source ${GLOBUS_LOCATION}/libexec/globus-sh-tools.sh
+globus_source ${libexecdir}/globus-sh-tools.sh
 
 if [ ! -z "${GRID_SECURITY_DIR}" ] ; then
     if [ -r "${GRID_SECURITY_DIR}/globus-user-ssl.conf" ] && 
@@ -57,10 +57,13 @@ if [ ! -z "${GRID_SECURITY_DIR}" ] ; then
         if test ! -z "${X509_CERT_DIR}" ; then
             trusted_certs_dir="${X509_CERT_DIR}"
         elif test "X`echo ${GRID_SECURITY_DIR}|sed 's/etc$//'|sed 's/\/$//'`" \
-            = "X`echo ${GLOBUS_LOCATION}|sed 's/\/$//'`" ; then
-            trusted_certs_dir="${GLOBUS_LOCATION}/share/certificates"
-        else
+            = "X`echo ${GLOBUS_LOCATION:-/usr}|sed 's/\/$//'`" ; then
+            trusted_certs_dir="${GLOBUS_LOCATION:-/usr}/share/certificates"
+        elif test -d "${secconfdir}/certificates"; then
             trusted_certs_dir="${secconfdir}/certificates"
+        else
+            echo "ERROR: Cannot determine trusted certificate directory. Please set X509_CERT_DIR" 1>&2
+            exit 1
         fi
     fi
 elif [ -r "/etc/grid-security/globus-user-ssl.conf" ] && 
@@ -77,7 +80,7 @@ elif [ -r "${GLOBUS_LOCATION}/etc/globus-user-ssl.conf" ] &&
     if test ! -z "${X509_CERT_DIR}" ; then
         trusted_certs_dir="${X509_CERT_DIR}"
     else
-        trusted_certs_dir="${GLOBUS_LOCATION}/share/certificates"
+        trusted_certs_dir="${GLOBUS_LOCATION:-/usr}/share/certificates"
     fi
 fi
 
@@ -189,9 +192,9 @@ set_non_default_ca()
         for cert in ${trusted_certs_dir}/*.0; do
             if test -r "${cert}" ; then
                 eval "CA${index}=${cert}"
-                TEMP_SUBJECT=`openssl x509 -in ${cert} -noout -subject`
+                TEMP_SUBJECT=`${SSL_EXEC} x509 -in ${cert} -noout -subject`
                 eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
-                eval "CA_HASH${index}=`openssl x509 -in ${cert} -noout -hash`"
+                eval "CA_HASH${index}=`${SSL_EXEC} x509 -in ${cert} -noout -hash`"
                 eval "echo \"$index)  \${CA_HASH${index}} - \${CA_SUBJECT${index}}\""
                 index=`expr $index + 1`
             fi
@@ -218,7 +221,7 @@ set_non_default_ca()
             echo 
             exit 1
         fi
-        TEMP_SUBJECT=`openssl x509 -in ${trusted_certs_dir}/${CA_HASH}.0 -noout -subject`
+        TEMP_SUBJECT=`${SSL_EXEC} x509 -in ${trusted_certs_dir}/${CA_HASH}.0 -noout -subject`
         eval "CA_SUBJECT=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
     fi
 
@@ -813,8 +816,17 @@ emit_directions () {
 
 
 #SSL related variables
-PATH=${GLOBUS_LOCATION}/bin:${PATH}
-SSL_EXEC="${GLOBUS_LOCATION}/bin/openssl"
+if test -n "${GLOBUS_LOCATION}" -a -x ${bindir}/openssl; then
+    SSL_EXEC=${bindir}/openssl
+else
+    SSL_EXEC="openssl"
+fi
+
+if ! ${SSL_EXEC} version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+    exit 1
+fi
+
 SSL_CONFIG="${secconfdir}/globus-user-ssl.conf"
 SSL_USER_CONFIG="${secconfdir}/globus-user-ssl.conf"
 SSL_HOST_CONFIG="${secconfdir}/globus-host-ssl.conf"
diff --git a/gsi/cert_utils/source/programs/grid-change-pass-phrase.in b/gsi/cert_utils/source/programs/grid-change-pass-phrase.in
--- a/gsi/cert_utils/source/programs/grid-change-pass-phrase.in
+++ b/gsi/cert_utils/source/programs/grid-change-pass-phrase.in
@@ -20,16 +20,16 @@
 # Change the pass phrase on a user's private key
 #
 
-if test -z "${GLOBUS_LOCATION}"; then
-    echo ""
-    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before"
-    echo "running this script"
-    echo ""
+if test -f ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer
+elif test -f ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer
+else
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before" 1>&2
+    echo "running this script" 1>&2
     exit 1
 fi
-
-. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
-globus_source ${GLOBUS_LOCATION}/libexec/globus-sh-tools.sh
+globus_source ${libexecdir}/globus-sh-tools.sh
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} -e 's|.*/||g'`
 
@@ -69,12 +69,16 @@ EOF
 globus_source $libexecdir/globus-args-parser-header $@
 
 # SSL related need
-PATH="${GLOBUS_LOCATION}/bin:${PATH}"
-SSLEAY=${GLOBUS_LOCATION}/bin/ssleay
-if [ -r ${GLOBUS_LOCATION}/bin/openssl ]; then
-    SSLEAY="${GLOBUS_LOCATION}/bin/openssl"
+if test -n "${GLOBUS_LOCATION}" -a -x ${bindir}/openssl; then
+    SSLEAY=${bindir}/openssl;
+else
+    SSLEAY="openssl"
 fi
 
+if ! ${SSLEAY} version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+    exit 1
+fi
 
 # DEFault Generated Files
 DEF_GLOBUS_DIR="${HOME}/.globus"
diff --git a/gsi/cert_utils/source/programs/grid-default-ca.in b/gsi/cert_utils/source/programs/grid-default-ca.in
--- a/gsi/cert_utils/source/programs/grid-default-ca.in
+++ b/gsi/cert_utils/source/programs/grid-default-ca.in
@@ -92,7 +92,7 @@ show_default() {
 
     for x in "$@"; do
         if test -f "${x}/$DEFAULTCAHASH.0"; then
-            DEFAULT_SUBJECT=`openssl x509 -in ${x}/$DEFAULTCAHASH.0 -noout -subject | ${GLOBUS_SH_SED-sed} -e "s|subject= ||"`
+            DEFAULT_SUBJECT=`${SSL_EXEC} x509 -in ${x}/$DEFAULTCAHASH.0 -noout -subject | ${GLOBUS_SH_SED-sed} -e "s|subject= ||"`
             echo
             echo "The default CA is: $DEFAULT_SUBJECT"
             echo "         Location: ${x}/$DEFAULTCAHASH.0"
@@ -120,7 +120,7 @@ ca_list() {
         for cert in ${cert_hashes}; do
             if test -r "${cert}" ; then 
                 eval "CA${index}=${cert}"
-                TEMP_SUBJECT=`openssl x509 -in ${cert} -noout -subject`
+                TEMP_SUBJECT=`${SSL_EXEC} x509 -in ${cert} -noout -subject`
                 eval "CA_SUBJECT${index}=\"`echo ${TEMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e \"s|subject= ||\"`\""
                 TEMP_HASH=`echo ${cert} | ${GLOBUS_SH_SED-sed} -e  "s|.*/\([^/]*\)\.0|\1|"`
                 eval "CA_HASH${index}=$TEMP_HASH"
@@ -236,15 +236,16 @@ EOF
 ############################################################
 # main code section
 ############################################################
-if test -z "${GLOBUS_LOCATION}"; then
-    echo 
-    echo "ERROR: Please set the GLOBUS_LOCATION to the Globus"
-    echo "installation directory before running this script."
-    echo
+
+if test -f ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/share/globus/globus-script-initializer
+elif test -f ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer; then
+    . ${GLOBUS_LOCATION:-/usr}/libexec/globus-script-initializer
+else
+    echo "ERROR: Please set GLOBUS_LOCATION to the Globus installation directory before" 1>&2
+    echo "running this script" 1>&2
     exit 1
 fi
-
-. ${GLOBUS_LOCATION}/libexec/globus-script-initializer
 globus_source ${libexecdir}/globus-sh-tools.sh
 
 PROGRAM_NAME=`echo $0 | ${GLOBUS_SH_SED-sed} 's|.*/||g'`
@@ -261,6 +262,17 @@ DIRT_BRANCH_ID="@DIRT_BRANCH_ID@"
 short_usage="$PROGRAM_NAME [-help] [ options ...]"
 
 . $libexecdir/globus-args-parser-header
+
+if test -n "${GLOBUS_LOCATION}" -a -x ${bindir}/openssl; then
+    SSL_EXEC=${bindir}/openssl
+else
+    SSL_EXEC="openssl"
+fi
+
+if ! ${SSL_EXEC} version > /dev/null 2> /dev/null; then
+    echo "Unable to locate openssl binary in $bindir or PATH" 1>&2
+    exit 1
+fi
 
 readCommandLine "$@"
 
@@ -280,8 +292,8 @@ fi
 if test -d "/etc/grid-security/certificates/." ; then
     set -- "$@" "/etc/grid-security/certificates" 
 fi
-if test -d "${GLOBUS_LOCATION}/share/certificates/."; then
-    set -- "$@" "${GLOBUS_LOCATION}/share/certificates"
+if test -d "${GLOBUS_LOCATION:-/usr}/share/certificates/."; then
+    set -- "$@" "${GLOBUS_LOCATION:-/usr}/share/certificates"
 fi
 
 found_ca=0
@@ -325,7 +337,7 @@ else
         echo 
         exit 1
     fi
-    TMP_SUBJECT=`openssl x509 -in ${CA_CERT} -noout -subject`
+    TMP_SUBJECT=`${SSL_EXEC} x509 -in ${CA_CERT} -noout -subject`
     CA_SUBJECT=`echo ${TMP_SUBJECT} | ${GLOBUS_SH_SED-sed} -e "s|subject= ||"`
 fi
 
@@ -344,7 +356,7 @@ echo
 echo "setting the default CA to: ${CA_SUBJECT}"
 echo
 
-NEW_DEFAULT_CA_HASH=`openssl x509 -in ${CA_CERT} -noout -hash`
+NEW_DEFAULT_CA_HASH=`${SSL_EXEC} x509 -in ${CA_CERT} -noout -hash`
 
 GRID_SECURITY_FILE=${CA_CERT_DIR}/grid-security.conf.${NEW_DEFAULT_CA_HASH}
 CA_SSL_HOST_CONFIG_FILE=${CA_CERT_DIR}/globus-host-ssl.conf.${NEW_DEFAULT_CA_HASH}
