GRAM-241: Improve init scripts for GT5.2 - Update globus-gatekeeper and globus-scheduler-event-generator init scripts   + Add missing actions from     http://fedoraproject.org/wiki/Packaging:SysVInitScript   + Add subsystem lock files   + Improve pidfile handling - Update spec files   + New versions   + Add --with-lsb to configure lines and lsb Requirements   + Add %post/%pre hooks to be more in line with fedora policy   + Mark /etc/sysconfig/* files as %config(noreplace) to avoid clobbering     site changes

diff --git a/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-lsb.in b/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-lsb.in
--- a/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-lsb.in
+++ b/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-lsb.in
@@ -14,13 +14,31 @@
 #                    It is part of the Globus Toolkit(tm)
 ### END INIT INFO
 
+# Copyright 1999-2011 University of Chicago
+# 
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# 
+# http://www.apache.org/licenses/LICENSE-2.0
+# 
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
 @GLOBUS_SCRIPT_INITIALIZER@
 
 . ${libexecdir}/globus-script-initializer
+progname="globus-scheduler-event-generator"
 
 GLOBUS_SEG_CONFIG=${GLOBUS_SEG_CONFIG:-@SEG_CONFIGDIR@/@SEG_CONFIGFILE@}
 test -f "${GLOBUS_SEG_CONFIG}" && . "${GLOBUS_SEG_CONFIG}"
 test -f ${sbindir}/globus-scheduler-event-generator || exit 0
+prog="${sbindir}/globus-scheduler-event-generator"
+lockfile="@LOCKFILE@"
 
 . /lib/lsb/init-functions
 GLOBUS_SEG_LRM_DIR="${GLOBUS_SEG_LRM_DIR:-${sysconfdir}/globus/scheduler-event-generator}"
@@ -38,56 +56,145 @@ GLOBUS_SEG_PIDFMT="${GLOBUS_SEG_PIDFMT:-${localstatedir}/run/globus-scheduler-ev
 GLOBUS_SEG_LOGFMT="${GLOBUS_SEG_LOGFMT:-${localstatedir}/globus/globus-seg-%s}"
 GLOBUS_SEG_LRM_DIR="${GLOBUS_SEG_LRM_DIR:-${sysconfdir}/globus/scheduler-event-generator}"
 
-case "$1" in
-    start)
-        allrc=0
-        for lrm in $lrms; do
-            pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
-            logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
-            if [ ! -d "$logdir" ]; then
-                (umask 022; mkdir "$logdir")
-            fi
-            start_daemon -p "$pidfile" \
-                ${sbindir}/globus-scheduler-event-generator \
-                -s "$lrm" \
-                -p "$pidfile" \
-                -d "$logdir" \
-                -b
+start()
+{
+    allrc=0
+    started=""
+    failed=""
+    for lrm in $lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
+        if [ ! -d "$logdir" ]; then
+            (umask 022; mkdir "$logdir")
+        fi
+        start_daemon ${GLOBUS_SEG_NICE_LEVEL:+-n "${GLOBUS_SEG_NICE_LEVEL}"} \
+            -p "$pidfile" "${prog}" \
+            -s "$lrm" \
+            -p "$pidfile" \
+            -d "$logdir" \
+            -b > /dev/null
+        rc=$?
+        if [ $rc = 0 ]; then
+            started="${started:+${started}, }$lrm"
+        else
+            failed="${failed:+${failed}, }$lrm"
+            allrc=$rc
+        fi
+    done
+    if [ "$allrc" -eq 0 -a "$started" != "" ]; then
+        log_success_msg "Started globus-scheduler-event-generator for ($started)"
+        touch "$lockfile"
+    elif [ "$allrc" -eq 0 ]; then
+        log_warning_msg "$progname: No LRMs installed"
+    elif [ "$started" = "" ]; then
+        log_failure_msg "Failed to start globus-scheduler-event-generator for ($failed)"
+    else
+        log_success_msg "Some problems starting globus-scheduler-event-generator for ($failed), but ($started) were ok"
+        touch "$lockfile"
+    fi
+    return $allrc
+}
+
+stop()
+{
+    allrc=0
+    stopped=""
+    failed=""
+    for lrm in $lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
+
+        if [ -f "$pidfile" ]; then
+            killproc -p "$pidfile" "${prog}"
             rc=$?
             if [ $rc = 0 ]; then
-                log_success_msg "Started globus-scheduler-event-generator for $lrm"
+                stopped="${stopped:+$stopped, }$lrm"
             else
-                log_failure_msg "Failed to start globus-scheduler-event-generator for $lrm"
+                failed="${failed:+$failed, }$lrm"
                 allrc=$rc
             fi
-        done
-        exit $allrc
+        fi
+    done
+    if [ "$allrc" -eq 0 ]; then
+        log_success_msg "Stopped globus-scheduler-event-generator${stopped:+ for ($stopped)}"
+        rm -f "$lockfile"
+    elif [ "$stopped" = "" ]; then
+        log_failure_msg "Failed to stop globus-scheduler-event-generator for $failed"
+    else
+        log_success_msg "Some problems stopping globus-scheduler-event-generator for $failed, but $stopped were ok"
+    fi
+    return $allrc
+}
+
+restart()
+{
+    stop
+    start
+}
+
+status()
+{
+    allrc=0
+
+    for lrm in $lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        pid="$(pidofproc -p "${pidfile}" "${prog}")"
+        rc=$?
+        case $rc in
+            0)
+                echo "$progname ($lrm) is running (pid=$pid)"
+                ;;
+            1)
+                echo "Stale PID file for $progname ($lrm)"
+                ;;
+            2)
+                echo "Stale lock file for $progname"
+                ;;
+            3)
+                echo "$progname ($lrm) is not running"
+                ;;
+            *)
+                echo "Unknown status for $progname ($lrm)"
+                ;;
+        esac
+        if [ "$allrc" -eq 0 -a "$rc" -ne 0 ]; then
+            allrc=$rc
+        fi
+    done
+
+    if [ "$allrc" -eq 0 -a "$lrms" = "" ]; then
+        echo "$progname not running, no LRMs installed"
+        allrc=3
+    fi
+    return $allrc
+}
+
+case "$1" in
+    start)
+        start
         ;;
     stop)
-        allrc=0
-        for lrm in $lrms; do
-            pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
-            logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
-
-            if [ -f "$pidfile" ]; then
-                killproc -p "$pidfile" \
-                    ${sbindir}/globus-scheduler-event-generator
-                rc=$?
-                if [ $rc = 0 ]; then
-                    log_success_msg "Stopped globus-scheduler-event-generator for $lrm"
-                else
-                    log_failure_msg "Failed to stop globus-scheduler-event-generator for $lrm"
-                    allrc=$rc
-                fi
-            fi
-        done
-        exit $allrc
+        stop
         ;;
     restart)
-        $0 stop
-        $0 start
+        stop
+        start
+        ;;
+    reload)
+        exit 0
         ;;
     force-reload)
-        $0 restart
+        restart
+        ;;
+    status)
+        status
+        ;;
+    condrestart|try-restart)
+        status || exit 0
+        restart
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+        exit 2
         ;;
 esac
diff --git a/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-nolsb.in b/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-nolsb.in
--- a/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-nolsb.in
+++ b/ws-gram/job_monitoring/common/c/source/init/globus-scheduler-event-generator-nolsb.in
@@ -14,14 +14,31 @@
 #                    It is part of the Globus Toolkit(tm)
 ### END INIT INFO
 
+# Copyright 1999-2011 University of Chicago
+# 
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+# 
+# http://www.apache.org/licenses/LICENSE-2.0
+# 
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#
+
 @GLOBUS_SCRIPT_INITIALIZER@
 
 . ${libexecdir}/globus-script-initializer
-progname="$(basename $0)"
 
+progname=globus-scheduler-event-generator
 GLOBUS_SEG_CONFIG=${GLOBUS_SEG_CONFIG:-@SEG_CONFIGDIR@/@SEG_CONFIGFILE@}
 test -f "${GLOBUS_SEG_CONFIG}" && . "${GLOBUS_SEG_CONFIG}"
 test -f ${sbindir}/$progname || exit 0
+prog="${sbindir}/${progname}"
+lockfile="@LOCKFILE@"
 
 GLOBUS_SEG_LRM_DIR="${GLOBUS_SEG_LRM_DIR:-${sysconfdir}/globus/scheduler-event-generator}"
 
@@ -38,63 +55,168 @@ GLOBUS_SEG_PIDFMT="${GLOBUS_SEG_PIDFMT:-${localstatedir}/run/globus-scheduler-ev
 GLOBUS_SEG_LOGFMT="${GLOBUS_SEG_LOGFMT:-${localstatedir}/globus/globus-seg-%s}"
 GLOBUS_SEG_LRM_DIR="${GLOBUS_SEG_LRM_DIR:-${sysconfdir}/globus/scheduler-event-generator}"
 
+start()
+{
+    allrc=0
+    started=""
+    failed=""
+    for lrm in $lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
+
+        status $lrm > /dev/null
+        rc=$?
+        if [ $rc -eq 0 ]; then
+            continue
+        fi
+
+        if [ ! -d "$logdir" ]; then
+            (umask 022; mkdir "$logdir")
+        fi
+        ${GLOBUS_SEG_NICE_LEVEL:+nice -n "${GLOBUS_SEG_NICE_LEVEL}"} \
+            "${prog}" \
+            -s "$lrm" \
+            -p "$pidfile" \
+            -d "$logdir" \
+            -b > /dev/null
+        rc=$?
+        if [ $rc = 0 ]; then
+            started="${started:+${started}, }$lrm"
+        else
+            failed="${failed:+${failed}, }$lrm"
+            allrc=$rc
+        fi
+    done
+    if [ "$allrc" -eq 0 -a "$lrms" != "" ]; then
+        echo "Started globus-scheduler-event-generator${started:+ for ($started)}"
+        touch "$lockfile"
+    elif [ "$allrc" -eq 0 ]; then
+        echo "$progname: no LRMS installed"
+    elif [ "$started" = "" ]; then
+        echo "Failed to start globus-scheduler-event-generator for ($failed)"
+    else
+        echo "Some problems starting globus-scheduler-event-generator for ($failed), but ($started) were ok"
+        touch "$lockfile"
+    fi
+    return $allrc
+}
+
+stop()
+{
+    allrc=0
+    stopped=""
+    failed=""
+    for lrm in $lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
+
+        if [ -f "$pidfile" ]; then
+            read pid < "${pidfile}" 2> /dev/null
+            if [ "$pid" -gt 0 ] 2>/dev/null; then
+                if kill -0 "${pid}" 2> /dev/null; then
+                    kill -TERM "${pid}"
+                    if sleep 1 && kill -0 "${pid}" 2>/dev/null &&  \
+                        sleep 3 && kill -0 "${pid}" 2>/dev/null; then
+                        kill -KILL "${pid}"
+                    fi
+
+                    if kill -0 "${pid}" 2> /dev/null; then
+                        failed="${failed:+$failed, }$lrm"
+                        allrc=1
+                        continue
+                    fi
+                fi
+            fi
+            stopped="${stopped:+${stopped}, }$lrm"
+            rm -f "${pidfile}"
+        fi
+    done
+    if [ "$allrc" -eq 0 ]; then
+        echo "Stopped globus-scheduler-event-generator${stopped:+ for ($stopped)}"
+        rm -f "$lockfile"
+    elif [ "$stopped" = "" ]; then
+        echo "Failed to stop globus-scheduler-event-generator for $failed"
+    else
+        echo "Some problems stopping globus-scheduler-event-generator for $failed, but $stopped were ok"
+    fi
+    return $allrc
+}
+
+restart()
+{
+    stop
+    start
+}
+
+status()
+{
+    _lrms="$1"
+    running=0
+    stale=0
+    nopidfile=0
+
+    if [ "$_lrms" = "" ]; then
+        _lrms="$lrms"
+    fi
+    for lrm in $_lrms; do
+        pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
+        if [ -f "$pidfile" ]; then
+            read pid < "$pidfile" 2>/dev/null
+            if [ "$pid" -gt 0 ] 2>/dev/null; then
+                if ps -p "$pid" > /dev/null; then
+                    echo "$progname ($lrm) is running (pid=$pid)"
+                    running=1
+                else
+                    echo "Stale PID file for $progname ($lrm)"
+                    stale=1
+                fi
+            fi
+        else
+            echo "$progname ($lrm) is not running"
+        fi
+    done
+
+    if [ "$stale" -ne 0 ]; then
+        return 1
+    fi
+    if [ "$running" -eq 0 -a "$stale" -eq 0 -a "${lrms}" != "" -a -f "${lockfile}" ]; then
+        echo "Stale lock file for $progname"
+        return 2
+    fi
+
+    if [ "$running" -eq 1 ]; then
+        return 0
+    else
+        echo "$progname not running, no LRMs installed"
+        return 3
+    fi
+}
+
 case "$1" in
     start)
-        allrc=0
-        for lrm in $lrms; do
-            pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
-            logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
-            if [ ! -d "$logdir" ]; then
-                (umask 022; mkdir "$logdir")
-            fi
-            ${sbindir}/$progname -p "$pidfile" -d "$logdir" -b -s "$lrm"
-            if [ ! -f "${pidfile}" ]; then
-                sleep 1
-            fi
-            ok=0
-            if [ -f "${pidfile}" ]; then
-                pid="$(cat "$pidfile")"
-                if kill -0 "$pid" 2> /dev/null; then
-                    echo "Started $progname for $lrm"
-                    ok=1
-                fi
-            fi
-            if [ "$ok" -eq 0 ]; then
-                echo "Error starting $progname for $lrm"
-                allrc=1
-            fi
-        done
-        exit $allrc
+        start
         ;;
     stop)
-        for lrm in $lrms; do
-            pidfile="$(printf "$GLOBUS_SEG_PIDFMT" "$lrm")"
-            logdir="$(printf "$GLOBUS_SEG_LOGFMT" "$lrm")"
-
-            if [ -f "$pidfile" ]; then
-                pid="$(cat "$pidfile")"
-                if [ "$pid" -gt 0 ] >/dev/null; then
-                    kill -TERM "$pid"
-                    sleep 1
-                    if ! kill -0 "${pid}" 2> /dev/null; then
-                        rm -f "${pidfile}"
-                        echo "Stopped $progname for $lrm"
-                    fi
-                else
-                    rm -f "${pidfile}"
-                    echo "Removed stale pidfile for $lrm"
-                fi
-            else
-                echo "No $progname running for $lrm"
-            fi
-        done
-        exit
+        stop
         ;;
     restart)
-        $0 stop
-        $0 start
+        restart
+        ;;
+    reload)
+        exit 0
         ;;
     force-reload)
-        $0 restart
+        restart
+        ;;
+    status)
+        status
+        ;;
+    condrestart|try-restart)
+        status || exit 0
+        restart
+        ;;
+    *)
+        echo "Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
+        exit 2
         ;;
 esac
